-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mlp_P_L0_W_0_RAM_AUTO_1R1W is 
    generic(
        MEM_TYPE        : string    := "auto"; 
        DataWidth       : integer   := 16; 
        AddressWidth    : integer   := 7;
        AddressRange    : integer   := 128
    ); 
    port (
        address0    : in std_logic_vector(AddressWidth-1 downto 0); 
        ce0         : in std_logic; 
        d0          : in std_logic_vector(DataWidth-1 downto 0); 
        we0         : in std_logic; 
        q0          : out std_logic_vector(DataWidth-1 downto 0);
        address1    : in std_logic_vector(AddressWidth-1 downto 0); 
        ce1         : in std_logic; 
        d1          : in std_logic_vector(DataWidth-1 downto 0); 
        we1         : in std_logic; 
        q1          : out std_logic_vector(DataWidth-1 downto 0);
        reset           : in std_logic; 
        clk             : in std_logic 
    ); 
end entity; 

architecture rtl of mlp_P_L0_W_0_RAM_AUTO_1R1W is 

signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);


type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 
-- Init 
shared variable ram : mem_array := (
    0 => "1111111000110001", 1 => "0000000101101110", 2 => "0000000100101110", 3 => "1111111000111100", 
    4 => "0000000010011011", 5 => "1111110000101101", 6 => "1111111011011110", 7 => "1111110001110010", 
    8 => "0000001010101111", 9 => "0000000011001000", 10 => "0000001010011001", 11 => "0000000001000010", 
    12 => "0000000000001000", 13 => "0000001001100000", 14 => "0000001000010101", 15 => "0000001010000100", 
    16 => "1111110110110101", 17 => "1111110110001101", 18 => "0000001010111011", 19 => "0000001111101011", 
    20 => "0000001010000010", 21 => "1111111001101110", 22 => "0000001110001010", 23 => "0000000011010111", 
    24 => "0000000111011110", 25 => "1111110011001000", 26 => "1111111011100110", 27 => "1111111111101111", 
    28 => "0000001000100111", 29 => "0000000010110010", 30 => "0000001101101001", 31 => "0000001111100111", 
    32 => "0000001111110001", 33 => "0000000011111001", 34 => "0000001100011001", 35 => "0000001101011110", 
    36 => "1111111001011011", 37 => "1111110101010000", 38 => "1111111101100111", 39 => "1111110111110001", 
    40 => "0000001000101101", 41 => "1111110010111101", 42 => "1111111111111001", 43 => "1111111001000100", 
    44 => "1111110100011011", 45 => "0000001110010010", 46 => "1111111000101000", 47 => "0000001111100000", 
    48 => "0000000011101100", 49 => "0000001111000110", 50 => "0000001010110101", 51 => "1111110101010000", 
    52 => "1111110101010110", 53 => "0000000001001010", 54 => "0000001011010110", 55 => "1111111011011010", 
    56 => "1111111001111111", 57 => "0000000011101001", 58 => "1111111010000010", 59 => "1111111001000110", 
    60 => "1111110100010010", 61 => "1111110101000001", 62 => "1111111001011100", 63 => "1111110011011010", 
    64 => "0000001101100010", 65 => "0000000011010111", 66 => "1111110000101000", 67 => "1111111000000101", 
    68 => "0000000101100101", 69 => "0000000110100001", 70 => "1111110111110111", 71 => "1111110010110110", 
    72 => "0000001000010011", 73 => "0000000001000110", 74 => "1111110111111110", 75 => "1111111011011000", 
    76 => "0000000100100110", 77 => "0000000111110001", 78 => "0000001111110000", 79 => "1111110111000100", 
    80 => "1111110111110000", 81 => "1111111110011100", 82 => "0000000110000010", 83 => "1111111011100000", 
    84 => "1111110001101100", 85 => "0000001001011111", 86 => "1111111001100100", 87 => "1111110111001100", 
    88 => "1111110010110100", 89 => "1111111100011110", 90 => "1111111000110101", 91 => "0000000010010111", 
    92 => "0000001010101010", 93 => "0000001101001100", 94 => "1111111110011011", 95 => "1111111011011111", 
    96 => "1111111010110001", 97 => "0000001000101000", 98 => "1111111101111100", 99 => "0000000110011100", 
    100 => "1111110101000001", 101 => "0000000100111001", 102 => "1111110100111010", 103 => "1111111100101010", 
    104 => "1111110100111010", 105 => "0000001111101100", 106 => "1111111011000001", 107 => "1111110011111101", 
    108 => "1111111111110001", 109 => "1111110010100010", 110 => "1111111111000111", 111 => "1111110110001101", 
    112 => "0000001001111111", 113 => "0000000010101111", 114 => "1111110000011010", 115 => "1111110001000001", 
    116 => "1111111011010100", 117 => "1111111001000000", 118 => "1111110110101110", 119 => "0000000110100101", 
    120 => "0000000011110110", 121 => "0000001110100100", 122 => "0000001110010110", 123 => "1111110110100100", 
    124 => "0000000110011101", 125 => "1111111001101110", 126 => "1111110101111000", 127 => "0000001101110110"); -- 
attribute syn_ramstyle : string;
attribute syn_ramstyle of ram : variable is "auto";
attribute ram_style : string;
attribute ram_style of ram : variable is MEM_TYPE;

begin 


memory_access_guard_0: process (address0) 
begin
    address0_tmp <= address0;
--synthesis translate_off
    if (CONV_INTEGER(address0) > AddressRange-1) then
        address0_tmp <= (others => '0');
    else 
       address0_tmp <= address0;
    end if;
--synthesis translate_on
end process;   -- 




--  read first
p_memory_access_0: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= ram(CONV_INTEGER(address0_tmp));
            if (we0 = '1') then 
                ram(CONV_INTEGER(address0_tmp)) := d0; 
            end if; 
        end if;
    end if;
end process;


 
memory_access_guard_1: process (address1) 
begin
    address1_tmp <= address1;
--synthesis translate_off
    if (CONV_INTEGER(address1) > AddressRange-1) then
        address1_tmp <= (others => '0');
    else 
       address1_tmp <= address1;
    end if;
--synthesis translate_on
end process;   -- 




--  read first
p_memory_access_1: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce1 = '1') then 
            q1 <= ram(CONV_INTEGER(address1_tmp));
            if (we1 = '1') then 
                ram(CONV_INTEGER(address1_tmp)) := d1; 
            end if; 
        end if;
    end if;
end process;


 

end rtl;
