set SynModuleInfo {
  {SRCNAME __hls_fptosi_float_i32 MODELNAME p_hls_fptosi_float_i32 RTLNAME eclair_p_hls_fptosi_float_i32}
  {SRCNAME {forward_layer<4, 2>_Pipeline_ACCUM_O} MODELNAME forward_layer_4_2_Pipeline_ACCUM_O RTLNAME eclair_forward_layer_4_2_Pipeline_ACCUM_O
    SUBMODULES {
      {MODELNAME eclair_flow_control_loop_pipe_sequential_init RTLNAME eclair_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME eclair_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME {forward_layer<4, 2>} MODELNAME forward_layer_4_2_s RTLNAME eclair_forward_layer_4_2_s
    SUBMODULES {
      {MODELNAME eclair_sitofp_32ns_32_3_no_dsp_1 RTLNAME eclair_sitofp_32ns_32_3_no_dsp_1 BINDTYPE op TYPE sitofp IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME eclair_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME eclair_sparsemux_9_2_32_1_1 RTLNAME eclair_sparsemux_9_2_32_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME {backward_input<4, 2, float>} MODELNAME backward_input_4_2_float_s RTLNAME eclair_backward_input_4_2_float_s}
  {SRCNAME eclair MODELNAME eclair RTLNAME eclair IS_TOP 1
    SUBMODULES {
      {MODELNAME eclair_faddfsub_32ns_32ns_32_5_full_dsp_1 RTLNAME eclair_faddfsub_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME eclair_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME eclair_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME eclair_LUT_B0_ROM_1P_LUTRAM_1R RTLNAME eclair_LUT_B0_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_0_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_0_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_0_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_0_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_0_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_0_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_0_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_0_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_LUT_B1_ROM_1P_LUTRAM_1R RTLNAME eclair_LUT_B1_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_LUT_B2_ROM_1P_LUTRAM_1R RTLNAME eclair_LUT_B2_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_LUT_B3_ROM_1P_LUTRAM_1R RTLNAME eclair_LUT_B3_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_1_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_1_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_1_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_1_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_1_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_1_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_1_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_1_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_2_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_2_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_2_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_2_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_2_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_2_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_2_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_2_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_3_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_3_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_3_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_3_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_3_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_3_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_0_3_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_0_3_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_0_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_0_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_0_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_0_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_0_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_0_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_0_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_0_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_1_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_1_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_1_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_1_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_1_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_1_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_1_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_1_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_2_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_2_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_2_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_2_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_2_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_2_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_2_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_2_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_3_0_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_3_0_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_3_1_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_3_1_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_3_2_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_3_2_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME eclair_p_ZL1P_1_3_3_RAM_2P_LUTRAM_1R1W RTLNAME eclair_p_ZL1P_1_3_3_RAM_2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
