-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mlp_backward_input_1_128_ap_fixed_16_6_4_0_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    dL_dy_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    dL_dy_ce0 : OUT STD_LOGIC;
    dL_dy_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy : IN STD_LOGIC_VECTOR (15 downto 0);
    C_C0_z_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    C_C0_z_ce0 : OUT STD_LOGIC;
    C_C0_z_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    P_L0_b_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    P_L0_b_ce0 : OUT STD_LOGIC;
    P_L0_b_we0 : OUT STD_LOGIC;
    P_L0_b_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    P_L0_b_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    P_L0_b_ce1 : OUT STD_LOGIC;
    P_L0_b_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    P_L0_W_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    P_L0_W_0_ce0 : OUT STD_LOGIC;
    P_L0_W_0_we0 : OUT STD_LOGIC;
    P_L0_W_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    P_L0_W_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    P_L0_W_0_ce1 : OUT STD_LOGIC;
    P_L0_W_0_we1 : OUT STD_LOGIC;
    P_L0_W_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    P_L0_W_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of mlp_backward_input_1_128_ap_fixed_16_6_4_0_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal conv7_i_fu_175_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_i_reg_814 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln101_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln101_reg_819 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal P_L0_b_addr_reg_833 : STD_LOGIC_VECTOR (6 downto 0);
    signal P_L0_b_addr_reg_833_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal P_L0_W_0_addr_reg_839 : STD_LOGIC_VECTOR (6 downto 0);
    signal P_L0_W_0_addr_reg_839_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal P_L0_W_0_addr_reg_839_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln112_fu_360_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln112_reg_845 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_2822_reg_852 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln112_fu_374_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln112_reg_858 : STD_LOGIC_VECTOR (8 downto 0);
    signal P_L0_b_load_reg_863 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal and_ln116_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln116_reg_868 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln116_1_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln116_1_reg_872 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln116_2_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln116_2_reg_876 : STD_LOGIC_VECTOR (0 downto 0);
    signal P_L0_W_0_load_reg_885 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal and_ln122_4_fu_755_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_4_reg_895 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_6_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_6_reg_899 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln122_2_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln122_2_reg_903 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal zext_ln101_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal o_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln101_fu_193_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal C_C0_z_ce0_local : STD_LOGIC;
    signal dL_dy_ce0_local : STD_LOGIC;
    signal P_L0_b_ce1_local : STD_LOGIC;
    signal P_L0_b_we0_local : STD_LOGIC;
    signal P_L0_b_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln116_fu_507_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal P_L0_b_ce0_local : STD_LOGIC;
    signal P_L0_b_address0_local : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal P_L0_W_0_ce1_local : STD_LOGIC;
    signal P_L0_W_0_address1_local : STD_LOGIC_VECTOR (6 downto 0);
    signal P_L0_W_0_we1_local : STD_LOGIC;
    signal add_ln122_fu_627_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal P_L0_W_0_we0_local : STD_LOGIC;
    signal P_L0_W_0_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal P_L0_W_0_ce0_local : STD_LOGIC;
    signal icmp_ln15_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_218_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln109_fu_226_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_2818_fu_260_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2817_fu_252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dL_dz_o_fu_242_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln109_fu_274_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal dL_dz_o_1_fu_278_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2819_fu_284_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_1_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln109_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_2_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln109_1_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_1_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dL_dz_o_2_fu_328_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2820_fu_336_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_2821_fu_348_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln112_fu_344_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln112_1_fu_356_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal delta_fu_378_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2824_fu_403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2823_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln112_2_fu_387_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln112_fu_422_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal delta_3_fu_426_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln112_3_fu_432_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2825_fu_436_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_1_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_2_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_2_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_1_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_1_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal delta_4_fu_478_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln116_fu_486_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln116_1_fu_489_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln116_fu_493_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2826_fu_499_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2827_fu_512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln116_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln116_1_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln1_fu_554_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_791_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln122_fu_588_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2831_fu_604_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln122_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2829_fu_581_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln5_fu_572_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln122_fu_623_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2832_fu_634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2830_fu_597_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln122_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_661_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2834_fu_676_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln122_1_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_2_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_3_fu_691_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2833_fu_654_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_1_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln122_1_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_2_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_3_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln122_fu_697_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln122_3_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2828_fu_565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln122_1_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln122_4_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln122_1_fu_717_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_5_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln122_2_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln122_5_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_791_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_666 : BOOLEAN;
    signal ap_condition_673 : BOOLEAN;
    signal ap_condition_677 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component mlp_mac_mulsub_16s_16s_26s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mac_mulsub_16s_16s_26s_32_4_1_U403 : component mlp_mac_mulsub_16s_16s_26s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => delta_4_fu_478_p3,
        din1 => grp_fu_791_p1,
        din2 => shl_ln1_fu_554_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_791_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    o_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                o_fu_104 <= ap_const_lv8_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln101_fu_187_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                o_fu_104 <= add_ln101_fu_193_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                P_L0_W_0_addr_reg_839 <= zext_ln101_fu_199_p1(7 - 1 downto 0);
                P_L0_W_0_addr_reg_839_pp0_iter1_reg <= P_L0_W_0_addr_reg_839;
                P_L0_W_0_addr_reg_839_pp0_iter2_reg <= P_L0_W_0_addr_reg_839_pp0_iter1_reg;
                P_L0_b_addr_reg_833 <= zext_ln101_fu_199_p1(7 - 1 downto 0);
                P_L0_b_addr_reg_833_pp0_iter1_reg <= P_L0_b_addr_reg_833;
                and_ln116_1_reg_872 <= and_ln116_1_fu_538_p2;
                and_ln116_reg_868 <= and_ln116_fu_526_p2;
                icmp_ln101_reg_819 <= icmp_ln101_fu_187_p2;
                xor_ln116_2_reg_876 <= xor_ln116_2_fu_544_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                P_L0_W_0_load_reg_885 <= P_L0_W_0_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                P_L0_b_load_reg_863 <= P_L0_b_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    add_ln112_reg_845(20 downto 1) <= add_ln112_fu_360_p2(20 downto 1);
                and_ln122_4_reg_895 <= and_ln122_4_fu_755_p2;
                and_ln122_6_reg_899 <= and_ln122_6_fu_779_p2;
                or_ln122_2_reg_903 <= or_ln122_2_fu_785_p2;
                tmp_2822_reg_852 <= add_ln112_fu_360_p2(20 downto 20);
                    trunc_ln112_reg_858(8 downto 1) <= trunc_ln112_fu_374_p1(8 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                conv7_i_reg_814 <= conv7_i_fu_175_p1;
            end if;
        end if;
    end process;
    add_ln112_reg_845(0) <= '0';
    trunc_ln112_reg_858(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln101_fu_187_p2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln101_fu_187_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln101_fu_187_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    C_C0_z_address0 <= zext_ln101_fu_199_p1(7 - 1 downto 0);
    C_C0_z_ce0 <= C_C0_z_ce0_local;

    C_C0_z_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            C_C0_z_ce0_local <= ap_const_logic_1;
        else 
            C_C0_z_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_W_0_address0 <= P_L0_W_0_addr_reg_839_pp0_iter2_reg;
    P_L0_W_0_address1 <= P_L0_W_0_address1_local;

    P_L0_W_0_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, P_L0_W_0_addr_reg_839, P_L0_W_0_addr_reg_839_pp0_iter2_reg, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            P_L0_W_0_address1_local <= P_L0_W_0_addr_reg_839_pp0_iter2_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            P_L0_W_0_address1_local <= P_L0_W_0_addr_reg_839;
        else 
            P_L0_W_0_address1_local <= "XXXXXXX";
        end if; 
    end process;

    P_L0_W_0_ce0 <= P_L0_W_0_ce0_local;

    P_L0_W_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, and_ln122_4_reg_895, and_ln122_6_reg_899, or_ln122_2_reg_903, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_lv1_0 = and_ln122_4_reg_895) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln122_6_reg_899) and (or_ln122_2_reg_903 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln122_4_reg_895) and (or_ln122_2_reg_903 = ap_const_lv1_1)))) then 
            P_L0_W_0_ce0_local <= ap_const_logic_1;
        else 
            P_L0_W_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_W_0_ce1 <= P_L0_W_0_ce1_local;

    P_L0_W_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            P_L0_W_0_ce1_local <= ap_const_logic_1;
        else 
            P_L0_W_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_W_0_d0 <= P_L0_W_0_d0_local;

    P_L0_W_0_d0_local_assign_proc : process(and_ln122_4_reg_895, and_ln122_6_reg_899, ap_condition_666)
    begin
        if ((ap_const_boolean_1 = ap_condition_666)) then
            if ((ap_const_lv1_1 = and_ln122_4_reg_895)) then 
                P_L0_W_0_d0_local <= ap_const_lv16_7FFF;
            elsif (((ap_const_lv1_0 = and_ln122_4_reg_895) and (ap_const_lv1_1 = and_ln122_6_reg_899))) then 
                P_L0_W_0_d0_local <= ap_const_lv16_8000;
            else 
                P_L0_W_0_d0_local <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            P_L0_W_0_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    P_L0_W_0_d1 <= add_ln122_fu_627_p2;
    P_L0_W_0_we0 <= P_L0_W_0_we0_local;

    P_L0_W_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, and_ln122_4_reg_895, and_ln122_6_reg_899, or_ln122_2_reg_903, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_lv1_0 = and_ln122_4_reg_895) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln122_6_reg_899) and (or_ln122_2_reg_903 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln122_4_reg_895) and (or_ln122_2_reg_903 = ap_const_lv1_1)))) then 
            P_L0_W_0_we0_local <= ap_const_logic_1;
        else 
            P_L0_W_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_W_0_we1 <= P_L0_W_0_we1_local;

    P_L0_W_0_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            P_L0_W_0_we1_local <= ap_const_logic_1;
        else 
            P_L0_W_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_b_address0 <= P_L0_b_address0_local;

    P_L0_b_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, P_L0_b_addr_reg_833, P_L0_b_addr_reg_833_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, and_ln116_reg_868, and_ln116_1_reg_872, xor_ln116_2_reg_876, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln116_reg_868) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (xor_ln116_2_reg_876 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_0 = and_ln116_reg_868) and (ap_const_lv1_1 = and_ln116_1_reg_872) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (xor_ln116_2_reg_876 = ap_const_lv1_1)))) then 
            P_L0_b_address0_local <= P_L0_b_addr_reg_833_pp0_iter1_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            P_L0_b_address0_local <= P_L0_b_addr_reg_833;
        else 
            P_L0_b_address0_local <= "XXXXXXX";
        end if; 
    end process;

    P_L0_b_address1 <= zext_ln101_fu_199_p1(7 - 1 downto 0);
    P_L0_b_ce0 <= P_L0_b_ce0_local;

    P_L0_b_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, and_ln116_reg_868, and_ln116_1_reg_872, xor_ln116_2_reg_876, ap_enable_reg_pp0_iter1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln116_reg_868) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (xor_ln116_2_reg_876 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_0 = and_ln116_reg_868) and (ap_const_lv1_1 = and_ln116_1_reg_872) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (xor_ln116_2_reg_876 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            P_L0_b_ce0_local <= ap_const_logic_1;
        else 
            P_L0_b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_b_ce1 <= P_L0_b_ce1_local;

    P_L0_b_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            P_L0_b_ce1_local <= ap_const_logic_1;
        else 
            P_L0_b_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    P_L0_b_d0 <= P_L0_b_d0_local;

    P_L0_b_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln116_fu_507_p1, ap_condition_673, ap_condition_677)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_677)) then 
                P_L0_b_d0_local <= ap_const_lv16_7FFF;
            elsif ((ap_const_boolean_1 = ap_condition_673)) then 
                P_L0_b_d0_local <= ap_const_lv16_8000;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                P_L0_b_d0_local <= trunc_ln116_fu_507_p1;
            else 
                P_L0_b_d0_local <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            P_L0_b_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    P_L0_b_we0 <= P_L0_b_we0_local;

    P_L0_b_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, and_ln116_reg_868, and_ln116_1_reg_872, xor_ln116_2_reg_876, ap_enable_reg_pp0_iter1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln116_reg_868) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (xor_ln116_2_reg_876 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_0 = and_ln116_reg_868) and (ap_const_lv1_1 = and_ln116_1_reg_872) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (xor_ln116_2_reg_876 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            P_L0_b_we0_local <= ap_const_logic_1;
        else 
            P_L0_b_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln101_fu_193_p2 <= std_logic_vector(unsigned(o_fu_104) + unsigned(ap_const_lv8_1));
    add_ln112_fu_360_p2 <= std_logic_vector(signed(sext_ln112_fu_344_p1) + signed(sext_ln112_1_fu_356_p1));
    add_ln122_fu_627_p2 <= std_logic_vector(unsigned(trunc_ln5_fu_572_p4) + unsigned(zext_ln122_fu_623_p1));
    and_ln109_1_fu_322_p2 <= (xor_ln109_fu_292_p2 and or_ln109_1_fu_316_p2);
    and_ln109_fu_268_p2 <= (tmp_2818_fu_260_p3 and tmp_2817_fu_252_p3);
    and_ln112_1_fu_472_p2 <= (xor_ln112_fu_444_p2 and or_ln112_1_fu_466_p2);
    and_ln112_fu_416_p2 <= (tmp_2823_fu_391_p3 and or_ln112_fu_410_p2);
    and_ln116_1_fu_538_p2 <= (xor_ln116_1_fu_532_p2 and tmp_2826_fu_499_p3);
    and_ln116_fu_526_p2 <= (xor_ln116_fu_520_p2 and tmp_2827_fu_512_p3);
    and_ln122_1_fu_648_p2 <= (xor_ln122_fu_642_p2 and tmp_2830_fu_597_p3);
    and_ln122_2_fu_711_p2 <= (xor_ln122_1_fu_705_p2 and icmp_ln122_1_fu_670_p2);
    and_ln122_3_fu_725_p2 <= (icmp_ln122_2_fu_685_p2 and and_ln122_1_fu_648_p2);
    and_ln122_4_fu_755_p2 <= (xor_ln122_4_fu_749_p2 and or_ln122_1_fu_743_p2);
    and_ln122_5_fu_761_p2 <= (tmp_2832_fu_634_p3 and select_ln122_1_fu_717_p3);
    and_ln122_6_fu_779_p2 <= (xor_ln122_5_fu_767_p2 and empty_fu_773_p2);
    and_ln122_fu_617_p2 <= (tmp_2829_fu_581_p3 and or_ln122_fu_611_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state9 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_666_assign_proc : process(ap_CS_fsm_pp0_stage0, or_ln122_2_reg_903, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0)
    begin
                ap_condition_666 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (or_ln122_2_reg_903 = ap_const_lv1_1));
    end process;


    ap_condition_673_assign_proc : process(ap_CS_fsm_pp0_stage1, and_ln116_reg_868, and_ln116_1_reg_872, xor_ln116_2_reg_876, ap_block_pp0_stage1)
    begin
                ap_condition_673 <= ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_0 = and_ln116_reg_868) and (ap_const_lv1_1 = and_ln116_1_reg_872) and (xor_ln116_2_reg_876 = ap_const_lv1_1));
    end process;


    ap_condition_677_assign_proc : process(ap_CS_fsm_pp0_stage1, and_ln116_reg_868, xor_ln116_2_reg_876, ap_block_pp0_stage1)
    begin
                ap_condition_677 <= ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln116_reg_868) and (xor_ln116_2_reg_876 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln101_fu_187_p2)
    begin
        if ((icmp_ln101_fu_187_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        conv7_i_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy),32));

    dL_dy_address0 <= zext_ln101_fu_199_p1(7 - 1 downto 0);
    dL_dy_ce0 <= dL_dy_ce0_local;

    dL_dy_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            dL_dy_ce0_local <= ap_const_logic_1;
        else 
            dL_dy_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dL_dz_o_1_fu_278_p2 <= std_logic_vector(unsigned(dL_dz_o_fu_242_p4) + unsigned(zext_ln109_fu_274_p1));
    dL_dz_o_2_fu_328_p3 <= 
        ap_const_lv16_7FFF when (and_ln109_1_fu_322_p2(0) = '1') else 
        dL_dz_o_1_fu_278_p2;
    dL_dz_o_fu_242_p4 <= select_ln109_fu_226_p3(25 downto 10);
    delta_3_fu_426_p2 <= std_logic_vector(signed(sext_ln112_2_fu_387_p1) + signed(zext_ln112_fu_422_p1));
    delta_4_fu_478_p3 <= 
        ap_const_lv16_7FFF when (and_ln112_1_fu_472_p2(0) = '1') else 
        sext_ln112_3_fu_432_p1;
    delta_fu_378_p4 <= add_ln112_reg_845(20 downto 10);
    empty_fu_773_p2 <= (xor_ln122_2_fu_731_p2 and tmp_2828_fu_565_p3);
    grp_fu_791_p1 <= conv7_i_reg_814(16 - 1 downto 0);
    icmp_ln101_fu_187_p2 <= "1" when (o_fu_104 = ap_const_lv8_80) else "0";
    icmp_ln112_fu_398_p2 <= "0" when (trunc_ln112_reg_858 = ap_const_lv9_0) else "1";
    icmp_ln122_1_fu_670_p2 <= "1" when (tmp_s_fu_661_p4 = ap_const_lv5_1F) else "0";
    icmp_ln122_2_fu_685_p2 <= "1" when (tmp_2834_fu_676_p4 = ap_const_lv6_3F) else "0";
    icmp_ln122_3_fu_691_p2 <= "1" when (tmp_2834_fu_676_p4 = ap_const_lv6_0) else "0";
    icmp_ln122_fu_591_p2 <= "0" when (trunc_ln122_fu_588_p1 = ap_const_lv9_0) else "1";
    icmp_ln15_fu_212_p2 <= "1" when (signed(C_C0_z_q0) > signed(ap_const_lv16_0)) else "0";
    or_ln109_1_fu_316_p2 <= (xor_ln109_2_fu_310_p2 or tmp_2819_fu_284_p3);
    or_ln109_fu_298_p2 <= (xor_ln109_fu_292_p2 or tmp_2819_fu_284_p3);
    or_ln112_1_fu_466_p2 <= (xor_ln112_2_fu_460_p2 or tmp_2825_fu_436_p3);
    or_ln112_2_fu_449_p2 <= (xor_ln112_fu_444_p2 or tmp_2825_fu_436_p3);
    or_ln112_fu_410_p2 <= (tmp_2824_fu_403_p3 or icmp_ln112_fu_398_p2);
    or_ln122_1_fu_743_p2 <= (xor_ln122_3_fu_737_p2 or tmp_2832_fu_634_p3);
    or_ln122_2_fu_785_p2 <= (and_ln122_6_fu_779_p2 or and_ln122_4_fu_755_p2);
    or_ln122_fu_611_p2 <= (tmp_2831_fu_604_p3 or icmp_ln122_fu_591_p2);
    select_ln109_fu_226_p3 <= 
        shl_ln_fu_218_p3 when (icmp_ln15_fu_212_p2(0) = '1') else 
        ap_const_lv26_0;
    select_ln122_1_fu_717_p3 <= 
        and_ln122_2_fu_711_p2 when (and_ln122_1_fu_648_p2(0) = '1') else 
        icmp_ln122_2_fu_685_p2;
    select_ln122_fu_697_p3 <= 
        icmp_ln122_2_fu_685_p2 when (and_ln122_1_fu_648_p2(0) = '1') else 
        icmp_ln122_3_fu_691_p2;
        sext_ln112_1_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2821_fu_348_p3),21));

        sext_ln112_2_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_fu_378_p4),12));

        sext_ln112_3_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_3_fu_426_p2),16));

        sext_ln112_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2820_fu_336_p3),21));

        sext_ln116_1_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_4_fu_478_p3),17));

        sext_ln116_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(P_L0_b_load_reg_863),17));

    shl_ln1_fu_554_p3 <= (P_L0_W_0_load_reg_885 & ap_const_lv10_0);
    shl_ln_fu_218_p3 <= (dL_dy_q0 & ap_const_lv10_0);
    sub_ln116_fu_493_p2 <= std_logic_vector(signed(sext_ln116_fu_486_p1) - signed(sext_ln116_1_fu_489_p1));
    tmp_2817_fu_252_p3 <= select_ln109_fu_226_p3(9 downto 9);
    tmp_2818_fu_260_p3 <= select_ln109_fu_226_p3(10 downto 10);
    tmp_2819_fu_284_p3 <= dL_dz_o_1_fu_278_p2(15 downto 15);
    tmp_2820_fu_336_p3 <= (dL_dz_o_2_fu_328_p3 & ap_const_lv3_0);
    tmp_2821_fu_348_p3 <= (dL_dz_o_2_fu_328_p3 & ap_const_lv1_0);
    tmp_2823_fu_391_p3 <= add_ln112_reg_845(9 downto 9);
    tmp_2824_fu_403_p3 <= add_ln112_reg_845(10 downto 10);
    tmp_2825_fu_436_p3 <= sext_ln112_3_fu_432_p1(15 downto 15);
    tmp_2826_fu_499_p3 <= sub_ln116_fu_493_p2(16 downto 16);
    tmp_2827_fu_512_p3 <= sub_ln116_fu_493_p2(15 downto 15);
    tmp_2828_fu_565_p3 <= grp_fu_791_p3(31 downto 31);
    tmp_2829_fu_581_p3 <= grp_fu_791_p3(9 downto 9);
    tmp_2830_fu_597_p3 <= grp_fu_791_p3(25 downto 25);
    tmp_2831_fu_604_p3 <= grp_fu_791_p3(10 downto 10);
    tmp_2832_fu_634_p3 <= add_ln122_fu_627_p2(15 downto 15);
    tmp_2833_fu_654_p3 <= grp_fu_791_p3(26 downto 26);
    tmp_2834_fu_676_p4 <= grp_fu_791_p3(31 downto 26);
    tmp_fu_234_p3 <= select_ln109_fu_226_p3(25 downto 25);
    tmp_s_fu_661_p4 <= grp_fu_791_p3(31 downto 27);
    trunc_ln112_fu_374_p1 <= add_ln112_fu_360_p2(9 - 1 downto 0);
    trunc_ln116_fu_507_p1 <= sub_ln116_fu_493_p2(16 - 1 downto 0);
    trunc_ln122_fu_588_p1 <= grp_fu_791_p3(9 - 1 downto 0);
    trunc_ln5_fu_572_p4 <= grp_fu_791_p3(25 downto 10);
    xor_ln109_1_fu_304_p2 <= (tmp_fu_234_p3 xor ap_const_lv1_1);
    xor_ln109_2_fu_310_p2 <= (xor_ln109_1_fu_304_p2 xor or_ln109_fu_298_p2);
    xor_ln109_fu_292_p2 <= (tmp_fu_234_p3 xor ap_const_lv1_1);
    xor_ln112_1_fu_455_p2 <= (tmp_2822_reg_852 xor ap_const_lv1_1);
    xor_ln112_2_fu_460_p2 <= (xor_ln112_1_fu_455_p2 xor or_ln112_2_fu_449_p2);
    xor_ln112_fu_444_p2 <= (tmp_2822_reg_852 xor ap_const_lv1_1);
    xor_ln116_1_fu_532_p2 <= (tmp_2827_fu_512_p3 xor ap_const_lv1_1);
    xor_ln116_2_fu_544_p2 <= (tmp_2827_fu_512_p3 xor tmp_2826_fu_499_p3);
    xor_ln116_fu_520_p2 <= (tmp_2826_fu_499_p3 xor ap_const_lv1_1);
    xor_ln122_1_fu_705_p2 <= (tmp_2833_fu_654_p3 xor ap_const_lv1_1);
    xor_ln122_2_fu_731_p2 <= (ap_const_lv1_1 xor and_ln122_3_fu_725_p2);
    xor_ln122_3_fu_737_p2 <= (select_ln122_fu_697_p3 xor ap_const_lv1_1);
    xor_ln122_4_fu_749_p2 <= (tmp_2828_fu_565_p3 xor ap_const_lv1_1);
    xor_ln122_5_fu_767_p2 <= (ap_const_lv1_1 xor and_ln122_5_fu_761_p2);
    xor_ln122_fu_642_p2 <= (tmp_2832_fu_634_p3 xor ap_const_lv1_1);
    zext_ln101_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(o_fu_104),64));
    zext_ln109_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln109_fu_268_p2),16));
    zext_ln112_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln112_fu_416_p2),12));
    zext_ln122_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln122_fu_617_p2),16));
end behav;
