// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlp_mlp_Pipeline_FWD_O (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv7_i_i,
        layer1_out_address0,
        layer1_out_ce0,
        layer1_out_we0,
        layer1_out_d0,
        P_L0_b_address0,
        P_L0_b_ce0,
        P_L0_b_q0,
        P_L0_W_0_address0,
        P_L0_W_0_ce0,
        P_L0_W_0_q0,
        C_C0_z_address0,
        C_C0_z_ce0,
        C_C0_z_we0,
        C_C0_z_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] conv7_i_i;
output  [6:0] layer1_out_address0;
output   layer1_out_ce0;
output   layer1_out_we0;
output  [14:0] layer1_out_d0;
output  [6:0] P_L0_b_address0;
output   P_L0_b_ce0;
input  [15:0] P_L0_b_q0;
output  [6:0] P_L0_W_0_address0;
output   P_L0_W_0_ce0;
input  [15:0] P_L0_W_0_q0;
output  [6:0] C_C0_z_address0;
output   C_C0_z_ce0;
output   C_C0_z_we0;
output  [15:0] C_C0_z_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_158_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [31:0] conv7_i_i_cast_fu_146_p1;
reg  signed [31:0] conv7_i_i_cast_reg_474;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln35_fu_170_p1;
reg   [63:0] zext_ln35_reg_483;
reg   [63:0] zext_ln35_reg_483_pp0_iter1_reg;
wire   [31:0] mul_ln44_fu_185_p2;
reg   [31:0] mul_ln44_reg_499;
wire   [31:0] add_ln44_fu_202_p2;
reg   [31:0] add_ln44_reg_504;
reg   [0:0] tmp_reg_512;
wire   [0:0] icmp_ln44_fu_220_p2;
reg   [0:0] icmp_ln44_reg_518;
reg   [4:0] tmp_7_reg_523;
reg   [5:0] tmp_8_reg_528;
wire    ap_block_pp0_stage0;
reg   [7:0] o_fu_84;
wire   [7:0] add_ln35_fu_164_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_o_1;
reg    P_L0_b_ce0_local;
reg    P_L0_W_0_ce0_local;
reg    C_C0_z_we0_local;
wire   [15:0] z_o_3_fu_439_p3;
reg    C_C0_z_ce0_local;
reg    layer1_out_we0_local;
wire   [14:0] select_ln10_fu_458_p3;
reg    layer1_out_ce0_local;
wire  signed [15:0] mul_ln44_fu_185_p1;
wire   [25:0] shl_ln_fu_190_p3;
wire  signed [31:0] sext_ln44_1_fu_198_p1;
wire   [8:0] trunc_ln44_fu_216_p1;
wire   [0:0] tmp_3_fu_269_p3;
wire   [0:0] or_ln44_fu_276_p2;
wire   [0:0] tmp_1_fu_255_p3;
wire   [0:0] and_ln44_fu_281_p2;
wire   [15:0] z_o_1_fu_246_p4;
wire   [15:0] zext_ln44_fu_287_p1;
wire   [15:0] z_o_2_fu_291_p2;
wire   [0:0] tmp_4_fu_297_p3;
wire   [0:0] tmp_2_fu_262_p3;
wire   [0:0] xor_ln44_fu_305_p2;
wire   [0:0] and_ln44_1_fu_311_p2;
wire   [0:0] icmp_ln44_2_fu_329_p2;
wire   [0:0] icmp_ln44_3_fu_334_p2;
wire   [0:0] tmp_5_fu_317_p3;
wire   [0:0] icmp_ln44_1_fu_324_p2;
wire   [0:0] xor_ln44_1_fu_347_p2;
wire   [0:0] and_ln44_2_fu_353_p2;
wire   [0:0] and_ln44_3_fu_367_p2;
wire   [0:0] xor_ln44_2_fu_373_p2;
wire   [0:0] select_ln44_fu_339_p3;
wire   [0:0] xor_ln44_3_fu_384_p2;
wire   [0:0] or_ln44_1_fu_390_p2;
wire   [0:0] xor_ln44_4_fu_396_p2;
wire   [0:0] select_ln44_1_fu_359_p3;
wire   [0:0] and_ln44_5_fu_407_p2;
wire   [0:0] empty_fu_379_p2;
wire   [0:0] xor_ln44_5_fu_413_p2;
wire   [0:0] and_ln44_4_fu_401_p2;
wire   [0:0] and_ln44_6_fu_419_p2;
wire   [0:0] or_ln44_2_fu_433_p2;
wire   [15:0] select_ln44_2_fu_425_p3;
wire   [0:0] icmp_ln10_fu_452_p2;
wire   [14:0] trunc_ln39_fu_448_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 o_fu_84 = 8'd0;
#0 ap_done_reg = 1'b0;
end

mlp_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U1(
    .din0(P_L0_W_0_q0),
    .din1(mul_ln44_fu_185_p1),
    .dout(mul_ln44_fu_185_p2)
);

mlp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_158_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            o_fu_84 <= add_ln35_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_84 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln44_reg_504 <= add_ln44_fu_202_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conv7_i_i_cast_reg_474 <= conv7_i_i_cast_fu_146_p1;
        icmp_ln44_reg_518 <= icmp_ln44_fu_220_p2;
        mul_ln44_reg_499 <= mul_ln44_fu_185_p2;
        tmp_7_reg_523 <= {{add_ln44_fu_202_p2[31:27]}};
        tmp_8_reg_528 <= {{add_ln44_fu_202_p2[31:26]}};
        tmp_reg_512 <= add_ln44_fu_202_p2[32'd31];
        zext_ln35_reg_483[7 : 0] <= zext_ln35_fu_170_p1[7 : 0];
        zext_ln35_reg_483_pp0_iter1_reg[7 : 0] <= zext_ln35_reg_483[7 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_C0_z_ce0_local = 1'b1;
    end else begin
        C_C0_z_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_C0_z_we0_local = 1'b1;
    end else begin
        C_C0_z_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_L0_W_0_ce0_local = 1'b1;
    end else begin
        P_L0_W_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_L0_b_ce0_local = 1'b1;
    end else begin
        P_L0_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_o_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_o_1 = o_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer1_out_ce0_local = 1'b1;
    end else begin
        layer1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer1_out_we0_local = 1'b1;
    end else begin
        layer1_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_C0_z_address0 = zext_ln35_reg_483_pp0_iter1_reg;

assign C_C0_z_ce0 = C_C0_z_ce0_local;

assign C_C0_z_d0 = z_o_3_fu_439_p3;

assign C_C0_z_we0 = C_C0_z_we0_local;

assign P_L0_W_0_address0 = zext_ln35_fu_170_p1;

assign P_L0_W_0_ce0 = P_L0_W_0_ce0_local;

assign P_L0_b_address0 = zext_ln35_fu_170_p1;

assign P_L0_b_ce0 = P_L0_b_ce0_local;

assign add_ln35_fu_164_p2 = (ap_sig_allocacmp_o_1 + 8'd1);

assign add_ln44_fu_202_p2 = ($signed(sext_ln44_1_fu_198_p1) + $signed(mul_ln44_fu_185_p2));

assign and_ln44_1_fu_311_p2 = (xor_ln44_fu_305_p2 & tmp_2_fu_262_p3);

assign and_ln44_2_fu_353_p2 = (xor_ln44_1_fu_347_p2 & icmp_ln44_1_fu_324_p2);

assign and_ln44_3_fu_367_p2 = (icmp_ln44_2_fu_329_p2 & and_ln44_1_fu_311_p2);

assign and_ln44_4_fu_401_p2 = (xor_ln44_4_fu_396_p2 & or_ln44_1_fu_390_p2);

assign and_ln44_5_fu_407_p2 = (tmp_4_fu_297_p3 & select_ln44_1_fu_359_p3);

assign and_ln44_6_fu_419_p2 = (xor_ln44_5_fu_413_p2 & empty_fu_379_p2);

assign and_ln44_fu_281_p2 = (tmp_1_fu_255_p3 & or_ln44_fu_276_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv7_i_i_cast_fu_146_p1 = $signed(conv7_i_i);

assign empty_fu_379_p2 = (xor_ln44_2_fu_373_p2 & tmp_reg_512);

assign icmp_ln10_fu_452_p2 = (($signed(z_o_3_fu_439_p3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_158_p2 = ((ap_sig_allocacmp_o_1 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln44_1_fu_324_p2 = ((tmp_7_reg_523 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln44_2_fu_329_p2 = ((tmp_8_reg_528 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln44_3_fu_334_p2 = ((tmp_8_reg_528 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_220_p2 = ((trunc_ln44_fu_216_p1 != 9'd0) ? 1'b1 : 1'b0);

assign layer1_out_address0 = zext_ln35_reg_483_pp0_iter1_reg;

assign layer1_out_ce0 = layer1_out_ce0_local;

assign layer1_out_d0 = select_ln10_fu_458_p3;

assign layer1_out_we0 = layer1_out_we0_local;

assign mul_ln44_fu_185_p1 = conv7_i_i_cast_reg_474;

assign or_ln44_1_fu_390_p2 = (xor_ln44_3_fu_384_p2 | tmp_4_fu_297_p3);

assign or_ln44_2_fu_433_p2 = (and_ln44_6_fu_419_p2 | and_ln44_4_fu_401_p2);

assign or_ln44_fu_276_p2 = (tmp_3_fu_269_p3 | icmp_ln44_reg_518);

assign select_ln10_fu_458_p3 = ((icmp_ln10_fu_452_p2[0:0] == 1'b1) ? trunc_ln39_fu_448_p1 : 15'd0);

assign select_ln44_1_fu_359_p3 = ((and_ln44_1_fu_311_p2[0:0] == 1'b1) ? and_ln44_2_fu_353_p2 : icmp_ln44_2_fu_329_p2);

assign select_ln44_2_fu_425_p3 = ((and_ln44_4_fu_401_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln44_fu_339_p3 = ((and_ln44_1_fu_311_p2[0:0] == 1'b1) ? icmp_ln44_2_fu_329_p2 : icmp_ln44_3_fu_334_p2);

assign sext_ln44_1_fu_198_p1 = $signed(shl_ln_fu_190_p3);

assign shl_ln_fu_190_p3 = {{P_L0_b_q0}, {10'd0}};

assign tmp_1_fu_255_p3 = mul_ln44_reg_499[32'd9];

assign tmp_2_fu_262_p3 = add_ln44_reg_504[32'd25];

assign tmp_3_fu_269_p3 = add_ln44_reg_504[32'd10];

assign tmp_4_fu_297_p3 = z_o_2_fu_291_p2[32'd15];

assign tmp_5_fu_317_p3 = add_ln44_reg_504[32'd26];

assign trunc_ln39_fu_448_p1 = z_o_3_fu_439_p3[14:0];

assign trunc_ln44_fu_216_p1 = mul_ln44_fu_185_p2[8:0];

assign xor_ln44_1_fu_347_p2 = (tmp_5_fu_317_p3 ^ 1'd1);

assign xor_ln44_2_fu_373_p2 = (1'd1 ^ and_ln44_3_fu_367_p2);

assign xor_ln44_3_fu_384_p2 = (select_ln44_fu_339_p3 ^ 1'd1);

assign xor_ln44_4_fu_396_p2 = (tmp_reg_512 ^ 1'd1);

assign xor_ln44_5_fu_413_p2 = (1'd1 ^ and_ln44_5_fu_407_p2);

assign xor_ln44_fu_305_p2 = (tmp_4_fu_297_p3 ^ 1'd1);

assign z_o_1_fu_246_p4 = {{add_ln44_reg_504[25:10]}};

assign z_o_2_fu_291_p2 = (z_o_1_fu_246_p4 + zext_ln44_fu_287_p1);

assign z_o_3_fu_439_p3 = ((or_ln44_2_fu_433_p2[0:0] == 1'b1) ? select_ln44_2_fu_425_p3 : z_o_2_fu_291_p2);

assign zext_ln35_fu_170_p1 = ap_sig_allocacmp_o_1;

assign zext_ln44_fu_287_p1 = and_ln44_fu_281_p2;

always @ (posedge ap_clk) begin
    zext_ln35_reg_483[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_483_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp_mlp_Pipeline_FWD_O
