// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eclair_eclair,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.535312,HLS_SYN_LAT=45,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=397,HLS_SYN_LUT=24280,HLS_VERSION=2024_1}" *)

module eclair (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0,
        input_1,
        output_r,
        output_r_ap_vld,
        feedback
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] input_0;
input  [15:0] input_1;
output  [15:0] output_r;
output   output_r_ap_vld;
input  [15:0] feedback;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_r_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0;
reg   [7:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0;
reg   [3:0] P_0_address0;
reg    P_0_ce0;
reg    P_0_we0;
wire   [15:0] P_0_q0;
reg    P_0_ce1;
wire   [15:0] P_0_q1;
reg   [3:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1;
reg   [7:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1;
wire    ap_CS_fsm_state3;
wire    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start;
wire    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_done;
wire    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_idle;
wire    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_ready;
wire   [3:0] grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_address0;
wire    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_ce0;
wire    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_we0;
wire   [15:0] grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_d0;
wire    grp_forward_layer_2_1_s_fu_83_ap_start;
wire    grp_forward_layer_2_1_s_fu_83_ap_done;
wire    grp_forward_layer_2_1_s_fu_83_ap_idle;
wire    grp_forward_layer_2_1_s_fu_83_ap_ready;
wire   [3:0] grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0;
wire    grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0_ap_vld;
wire   [7:0] grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0;
wire    grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0_ap_vld;
wire   [3:0] grp_forward_layer_2_1_s_fu_83_P_0_address0;
wire    grp_forward_layer_2_1_s_fu_83_P_0_ce0;
wire   [3:0] grp_forward_layer_2_1_s_fu_83_P_0_address1;
wire    grp_forward_layer_2_1_s_fu_83_P_0_ce1;
wire   [3:0] grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1;
wire    grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1_ap_vld;
wire   [7:0] grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1;
wire    grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1_ap_vld;
wire   [15:0] grp_forward_layer_2_1_s_fu_83_ap_return;
reg    grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_forward_layer_2_1_s_fu_83_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0 = 4'd0;
#0 eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0 = 8'd0;
#0 eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1 = 4'd0;
#0 eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1 = 8'd0;
#0 grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start_reg = 1'b0;
#0 grp_forward_layer_2_1_s_fu_83_ap_start_reg = 1'b0;
end

eclair_P_0_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
P_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(P_0_address0),
    .ce0(P_0_ce0),
    .we0(P_0_we0),
    .d0(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_d0),
    .q0(P_0_q0),
    .address1(grp_forward_layer_2_1_s_fu_83_P_0_address1),
    .ce1(P_0_ce1),
    .q1(P_0_q1)
);

eclair_backward_input_2_1_ap_fixed_16_6_4_0_0_s grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start),
    .ap_done(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_done),
    .ap_idle(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_idle),
    .ap_ready(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_ready),
    .dL_dy_val(feedback),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0),
    .P_0_address0(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_address0),
    .P_0_ce0(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_ce0),
    .P_0_we0(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_we0),
    .P_0_d0(grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_d0),
    .P_0_q0(P_0_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1)
);

eclair_forward_layer_2_1_s grp_forward_layer_2_1_s_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_layer_2_1_s_fu_83_ap_start),
    .ap_done(grp_forward_layer_2_1_s_fu_83_ap_done),
    .ap_idle(grp_forward_layer_2_1_s_fu_83_ap_idle),
    .ap_ready(grp_forward_layer_2_1_s_fu_83_ap_ready),
    .x_0_val(input_0),
    .x_1_val(input_1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0_ap_vld(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0_ap_vld),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0_ap_vld(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0_ap_vld),
    .P_0_address0(grp_forward_layer_2_1_s_fu_83_P_0_address0),
    .P_0_ce0(grp_forward_layer_2_1_s_fu_83_P_0_ce0),
    .P_0_q0(P_0_q0),
    .P_0_address1(grp_forward_layer_2_1_s_fu_83_P_0_address1),
    .P_0_ce1(grp_forward_layer_2_1_s_fu_83_P_0_ce1),
    .P_0_q1(P_0_q1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1_ap_vld(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1_ap_vld),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1_ap_vld(grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1_ap_vld),
    .ap_return(grp_forward_layer_2_1_s_fu_83_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start_reg <= 1'b1;
        end else if ((grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_ready == 1'b1)) begin
            grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_layer_2_1_s_fu_83_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_forward_layer_2_1_s_fu_83_ap_start_reg <= 1'b1;
        end else if ((grp_forward_layer_2_1_s_fu_83_ap_ready == 1'b1)) begin
            grp_forward_layer_2_1_s_fu_83_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0 <= grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1 <= grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0 <= grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1 <= grp_forward_layer_2_1_s_fu_83_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        P_0_address0 = grp_forward_layer_2_1_s_fu_83_P_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        P_0_address0 = grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_address0;
    end else begin
        P_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        P_0_ce0 = grp_forward_layer_2_1_s_fu_83_P_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        P_0_ce0 = grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_ce0;
    end else begin
        P_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        P_0_ce1 = grp_forward_layer_2_1_s_fu_83_P_0_ce1;
    end else begin
        P_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P_0_we0 = grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_P_0_we0;
    end else begin
        P_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_layer_2_1_s_fu_83_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forward_layer_2_1_s_fu_83_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forward_layer_2_1_s_fu_83_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forward_layer_2_1_s_fu_83_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_r_ap_vld = 1'b1;
    end else begin
        output_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_forward_layer_2_1_s_fu_83_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start = grp_backward_input_2_1_ap_fixed_16_6_4_0_0_s_fu_67_ap_start_reg;

assign grp_forward_layer_2_1_s_fu_83_ap_start = grp_forward_layer_2_1_s_fu_83_ap_start_reg;

assign output_r = grp_forward_layer_2_1_s_fu_83_ap_return;

endmodule //eclair
