// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eclair_forward_layer_2_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_val,
        x_1_val,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0_ap_vld,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0_ap_vld,
        LUT_B0_address0,
        LUT_B0_ce0,
        LUT_B0_q0,
        LUT_B1_address0,
        LUT_B1_ce0,
        LUT_B1_q0,
        LUT_B2_address0,
        LUT_B2_ce0,
        LUT_B2_q0,
        LUT_B3_address0,
        LUT_B3_ce0,
        LUT_B3_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q1,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1_ap_vld,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1,
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1_ap_vld,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q0,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1,
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x_0_val;
input  [15:0] x_1_val;
output  [2:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0;
output   eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0_ap_vld;
output  [7:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0;
output   eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0_ap_vld;
output  [7:0] LUT_B0_address0;
output   LUT_B0_ce0;
input  [7:0] LUT_B0_q0;
output  [7:0] LUT_B1_address0;
output   LUT_B1_ce0;
input  [9:0] LUT_B1_q0;
output  [7:0] LUT_B2_address0;
output   LUT_B2_ce0;
input  [9:0] LUT_B2_q0;
output  [7:0] LUT_B3_address0;
output   LUT_B3_ce0;
input  [7:0] LUT_B3_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q1;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q1;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q1;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q1;
output  [2:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1;
output   eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1_ap_vld;
output  [7:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1;
output   eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1_ap_vld;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q1;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q1;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q1;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q0;
output  [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address1;
output   p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1;
input  [15:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q1;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0_ap_vld;
reg eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0_ap_vld;
reg eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1_ap_vld;
reg eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1_ap_vld;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] reg_596;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [0:0] tmp_2_fu_640_p3;
reg   [0:0] tmp_2_reg_2689;
wire   [15:0] t_1_fu_708_p2;
reg   [15:0] t_1_reg_2694;
wire   [0:0] and_ln12_1_fu_728_p2;
reg   [0:0] and_ln12_1_reg_2699;
wire   [0:0] icmp_ln12_2_fu_768_p2;
reg   [0:0] icmp_ln12_2_reg_2704;
wire   [0:0] and_ln12_4_fu_826_p2;
reg   [0:0] and_ln12_4_reg_2709;
wire   [0:0] xor_ln12_5_fu_838_p2;
reg   [0:0] xor_ln12_5_reg_2715;
wire   [0:0] tmp_10_fu_883_p3;
reg   [0:0] tmp_10_reg_2720;
wire    ap_CS_fsm_state2;
wire   [2:0] trunc_ln25_fu_939_p1;
reg   [2:0] trunc_ln25_reg_2725;
wire   [0:0] and_ln19_fu_1033_p2;
reg   [0:0] and_ln19_reg_2730;
wire  signed [15:0] u_fu_1067_p11;
reg  signed [15:0] u_reg_2735;
wire   [0:0] tmp_19_fu_1131_p3;
reg   [0:0] tmp_19_reg_2741;
wire   [15:0] t_4_fu_1199_p2;
reg   [15:0] t_4_reg_2746;
wire   [0:0] and_ln12_8_fu_1219_p2;
reg   [0:0] and_ln12_8_reg_2751;
wire   [0:0] icmp_ln12_6_fu_1259_p2;
reg   [0:0] icmp_ln12_6_reg_2756;
wire   [0:0] and_ln12_11_fu_1317_p2;
reg   [0:0] and_ln12_11_reg_2761;
wire   [0:0] xor_ln12_11_fu_1329_p2;
reg   [0:0] xor_ln12_11_reg_2767;
wire   [2:0] k_fu_1341_p9;
reg   [2:0] k_reg_2772;
wire    ap_CS_fsm_state3;
wire   [1:0] trunc_ln19_fu_1360_p1;
reg   [1:0] trunc_ln19_reg_2779;
wire   [0:0] tmp_27_fu_1495_p3;
reg   [0:0] tmp_27_reg_2787;
wire   [2:0] trunc_ln25_2_fu_1551_p1;
reg   [2:0] trunc_ln25_2_reg_2792;
wire   [0:0] and_ln19_1_fu_1645_p2;
reg   [0:0] and_ln19_1_reg_2797;
wire  signed [15:0] u_1_fu_1679_p11;
reg  signed [15:0] u_1_reg_2802;
wire   [2:0] k_1_fu_1729_p9;
reg   [2:0] k_1_reg_2848;
wire   [1:0] trunc_ln19_1_fu_1748_p1;
reg   [1:0] trunc_ln19_1_reg_2855;
reg   [9:0] b1_reg_2863;
reg   [7:0] b3_reg_2868;
reg   [0:0] tmp_41_reg_2918;
wire   [15:0] tmp_34_fu_1961_p11;
reg  signed [15:0] tmp_34_reg_2993;
reg   [9:0] b1_1_reg_3003;
reg   [7:0] b3_1_reg_3008;
reg   [0:0] tmp_53_reg_3058;
wire  signed [25:0] mul_ln76_1_fu_2103_p2;
wire    ap_CS_fsm_state6;
wire   [15:0] tmp_44_fu_2150_p11;
reg  signed [15:0] tmp_44_reg_3108;
wire    ap_CS_fsm_state7;
wire  signed [25:0] mul_ln76_5_fu_2209_p2;
wire  signed [26:0] grp_fu_2636_p3;
wire    ap_CS_fsm_state8;
wire  signed [15:0] o_sum_fu_2398_p3;
reg  signed [15:0] o_sum_reg_3148;
wire    ap_CS_fsm_state9;
wire  signed [26:0] grp_fu_2667_p3;
wire   [15:0] o_sum_1_fu_2571_p2;
reg   [15:0] o_sum_1_reg_3159;
wire    ap_CS_fsm_state10;
reg   [0:0] tmp_59_reg_3164;
reg   [0:0] tmp_60_reg_3170;
wire   [63:0] zext_ln70_fu_1715_p1;
wire   [63:0] zext_ln47_fu_1372_p1;
wire   [63:0] zext_ln76_fu_1861_p1;
wire   [63:0] zext_ln76_1_fu_1882_p1;
wire   [63:0] zext_ln70_1_fu_1942_p1;
wire   [63:0] zext_ln47_1_fu_1760_p1;
wire   [63:0] zext_ln76_2_fu_1954_p1;
wire   [63:0] zext_ln76_4_fu_2028_p1;
wire   [63:0] zext_ln76_5_fu_2049_p1;
wire   [63:0] zext_ln76_6_fu_2143_p1;
wire   [7:0] ui_fu_1448_p3;
wire   [7:0] ui_1_fu_1836_p3;
reg    LUT_B0_ce0_local;
reg   [7:0] LUT_B0_address0_local;
reg    LUT_B1_ce0_local;
reg   [7:0] LUT_B1_address0_local;
reg    LUT_B2_ce0_local;
reg   [7:0] LUT_B2_address0_local;
reg    LUT_B3_ce0_local;
reg   [7:0] LUT_B3_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0_local;
reg   [0:0] p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0_local;
reg    p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1_local;
wire  signed [16:0] sext_ln12_fu_600_p1;
wire   [16:0] add_ln12_fu_604_p2;
wire   [26:0] tmp_fu_610_p3;
wire   [24:0] tmp_1_fu_622_p3;
wire  signed [28:0] sext_ln12_1_fu_618_p1;
wire  signed [28:0] sext_ln12_3_fu_630_p1;
wire   [28:0] add_ln12_1_fu_634_p2;
wire   [8:0] trunc_ln12_fu_666_p1;
wire   [0:0] tmp_5_fu_684_p3;
wire   [0:0] icmp_ln12_fu_670_p2;
wire   [0:0] or_ln12_fu_692_p2;
wire   [0:0] tmp_3_fu_658_p3;
wire   [0:0] and_ln12_fu_698_p2;
wire   [15:0] t_fu_648_p4;
wire   [15:0] zext_ln12_fu_704_p1;
wire   [0:0] tmp_6_fu_714_p3;
wire   [0:0] tmp_4_fu_676_p3;
wire   [0:0] xor_ln12_fu_722_p2;
wire   [1:0] tmp_7_fu_742_p4;
wire   [2:0] tmp_8_fu_758_p4;
wire   [0:0] icmp_ln12_3_fu_774_p2;
wire   [0:0] tmp_9_fu_734_p3;
wire   [0:0] icmp_ln12_1_fu_752_p2;
wire   [0:0] xor_ln12_1_fu_788_p2;
wire   [0:0] and_ln12_2_fu_794_p2;
wire   [0:0] select_ln12_fu_780_p3;
wire   [0:0] xor_ln12_3_fu_808_p2;
wire   [0:0] or_ln12_1_fu_814_p2;
wire   [0:0] xor_ln12_4_fu_820_p2;
wire   [0:0] select_ln12_1_fu_800_p3;
wire   [0:0] and_ln12_5_fu_832_p2;
wire   [0:0] and_ln12_3_fu_844_p2;
wire   [0:0] xor_ln12_2_fu_848_p2;
wire   [0:0] empty_fu_854_p2;
wire   [0:0] and_ln12_6_fu_859_p2;
wire   [0:0] or_ln12_2_fu_871_p2;
wire   [15:0] select_ln12_2_fu_864_p3;
wire   [15:0] t_2_fu_876_p3;
wire   [9:0] trunc_ln24_fu_907_p1;
wire   [5:0] tmp_s_fu_897_p4;
wire   [0:0] icmp_ln24_fu_911_p2;
wire   [5:0] add_ln24_fu_917_p2;
wire   [5:0] select_ln24_fu_923_p3;
wire   [5:0] ref_tmp_i_i_i_0_fu_931_p3;
wire   [0:0] tmp_11_fu_943_p3;
wire   [15:0] shl_ln_fu_951_p3;
wire   [15:0] select_ln25_fu_959_p3;
wire   [16:0] zext_ln25_fu_967_p1;
wire   [16:0] zext_ln25_1_fu_971_p1;
wire   [16:0] sub_ln25_fu_975_p2;
wire   [0:0] tmp_12_fu_981_p3;
wire   [0:0] tmp_13_fu_993_p3;
wire   [0:0] xor_ln25_fu_1001_p2;
wire   [0:0] and_ln25_fu_1007_p2;
wire   [0:0] icmp_ln19_fu_891_p2;
wire   [0:0] xor_ln15_fu_1027_p2;
wire   [0:0] or_ln19_fu_1039_p2;
wire   [0:0] xor_ln25_1_fu_1013_p2;
wire   [0:0] xor_ln19_fu_1045_p2;
wire   [0:0] and_ln25_2_fu_1051_p2;
wire   [15:0] u_fu_1067_p6;
wire   [15:0] u_fu_1067_p8;
wire   [15:0] u_fu_1067_p9;
wire   [2:0] u_fu_1067_p10;
wire  signed [16:0] sext_ln12_2_fu_1091_p1;
wire   [16:0] add_ln12_2_fu_1095_p2;
wire   [26:0] tmp_17_fu_1101_p3;
wire   [24:0] tmp_18_fu_1113_p3;
wire  signed [28:0] sext_ln12_4_fu_1109_p1;
wire  signed [28:0] sext_ln12_5_fu_1121_p1;
wire   [28:0] add_ln12_4_fu_1125_p2;
wire   [8:0] trunc_ln12_1_fu_1157_p1;
wire   [0:0] tmp_22_fu_1175_p3;
wire   [0:0] icmp_ln12_4_fu_1161_p2;
wire   [0:0] or_ln12_3_fu_1183_p2;
wire   [0:0] tmp_20_fu_1149_p3;
wire   [0:0] and_ln12_7_fu_1189_p2;
wire   [15:0] t_3_fu_1139_p4;
wire   [15:0] zext_ln12_1_fu_1195_p1;
wire   [0:0] tmp_25_fu_1205_p3;
wire   [0:0] tmp_21_fu_1167_p3;
wire   [0:0] xor_ln12_6_fu_1213_p2;
wire   [1:0] tmp_23_fu_1233_p4;
wire   [2:0] tmp_24_fu_1249_p4;
wire   [0:0] icmp_ln12_7_fu_1265_p2;
wire   [0:0] tmp_26_fu_1225_p3;
wire   [0:0] icmp_ln12_5_fu_1243_p2;
wire   [0:0] xor_ln12_7_fu_1279_p2;
wire   [0:0] and_ln12_9_fu_1285_p2;
wire   [0:0] select_ln12_4_fu_1271_p3;
wire   [0:0] xor_ln12_9_fu_1299_p2;
wire   [0:0] or_ln12_4_fu_1305_p2;
wire   [0:0] xor_ln12_10_fu_1311_p2;
wire   [0:0] select_ln12_5_fu_1291_p3;
wire   [0:0] and_ln12_12_fu_1323_p2;
wire   [2:0] k_fu_1341_p7;
wire   [1:0] k_fu_1341_p8;
wire   [0:0] tmp_14_fu_1364_p3;
wire   [30:0] tmp_15_fu_1383_p3;
wire  signed [31:0] sext_ln49_2_fu_1390_p1;
wire  signed [31:0] sext_ln49_fu_1380_p1;
wire   [31:0] sub_ln49_fu_1394_p2;
wire   [31:0] add_ln49_fu_1400_p2;
wire   [19:0] trunc_ln49_fu_1424_p1;
wire   [7:0] tmp_14_cast1_fu_1406_p4;
wire   [0:0] icmp_ln49_fu_1428_p2;
wire   [7:0] add_ln49_1_fu_1434_p2;
wire   [0:0] tmp_16_fu_1416_p3;
wire   [7:0] select_ln49_fu_1440_p3;
wire   [0:0] and_ln12_10_fu_1456_p2;
wire   [0:0] xor_ln12_8_fu_1460_p2;
wire   [0:0] empty_14_fu_1466_p2;
wire   [0:0] and_ln12_13_fu_1471_p2;
wire   [0:0] or_ln12_5_fu_1483_p2;
wire   [15:0] select_ln12_6_fu_1476_p3;
wire   [15:0] t_5_fu_1488_p3;
wire   [9:0] trunc_ln24_1_fu_1519_p1;
wire   [5:0] tmp_28_fu_1509_p4;
wire   [0:0] icmp_ln24_1_fu_1523_p2;
wire   [5:0] add_ln24_1_fu_1529_p2;
wire   [5:0] select_ln24_1_fu_1535_p3;
wire   [5:0] ref_tmp_i_i_i_0_1_fu_1543_p3;
wire   [0:0] tmp_29_fu_1555_p3;
wire   [15:0] shl_ln25_1_fu_1563_p3;
wire   [15:0] select_ln25_2_fu_1571_p3;
wire   [16:0] zext_ln25_2_fu_1579_p1;
wire   [16:0] zext_ln25_3_fu_1583_p1;
wire   [16:0] sub_ln25_1_fu_1587_p2;
wire   [0:0] tmp_30_fu_1593_p3;
wire   [0:0] tmp_31_fu_1605_p3;
wire   [0:0] xor_ln25_2_fu_1613_p2;
wire   [0:0] and_ln25_1_fu_1619_p2;
wire   [0:0] icmp_ln19_1_fu_1503_p2;
wire   [0:0] xor_ln15_1_fu_1639_p2;
wire   [0:0] or_ln19_1_fu_1651_p2;
wire   [0:0] xor_ln25_3_fu_1625_p2;
wire   [0:0] xor_ln19_1_fu_1657_p2;
wire   [0:0] and_ln25_3_fu_1663_p2;
wire   [15:0] u_1_fu_1679_p6;
wire   [15:0] u_1_fu_1679_p8;
wire   [15:0] u_1_fu_1679_p9;
wire   [2:0] u_1_fu_1679_p10;
wire   [2:0] k_1_fu_1729_p7;
wire   [1:0] k_1_fu_1729_p8;
wire   [0:0] tmp_32_fu_1752_p3;
wire   [30:0] tmp_37_fu_1771_p3;
wire  signed [31:0] sext_ln49_3_fu_1778_p1;
wire  signed [31:0] sext_ln49_1_fu_1768_p1;
wire   [31:0] sub_ln49_1_fu_1782_p2;
wire   [31:0] add_ln49_2_fu_1788_p2;
wire   [19:0] trunc_ln49_1_fu_1812_p1;
wire   [7:0] tmp_32_cast1_fu_1794_p4;
wire   [0:0] icmp_ln49_1_fu_1816_p2;
wire   [7:0] add_ln49_3_fu_1822_p2;
wire   [0:0] tmp_38_fu_1804_p3;
wire   [7:0] select_ln49_1_fu_1828_p3;
wire   [2:0] add_ln76_fu_1848_p2;
wire   [0:0] tmp_39_fu_1853_p3;
wire   [2:0] add_ln76_1_fu_1869_p2;
wire   [0:0] tmp_40_fu_1874_p3;
wire   [2:0] add_ln76_2_fu_1890_p2;
wire   [15:0] tmp_33_fu_1903_p9;
wire  signed [15:0] tmp_33_fu_1903_p11;
wire   [15:0] tmp_34_fu_1961_p9;
wire   [15:0] tmp_35_fu_1984_p9;
wire  signed [15:0] tmp_35_fu_1984_p11;
wire   [2:0] add_ln76_7_fu_2015_p2;
wire   [0:0] tmp_51_fu_2020_p3;
wire   [2:0] add_ln76_8_fu_2036_p2;
wire   [0:0] tmp_52_fu_2041_p3;
wire   [2:0] add_ln76_9_fu_2057_p2;
wire   [15:0] tmp_43_fu_2070_p9;
wire  signed [15:0] tmp_43_fu_2070_p11;
wire   [9:0] mul_ln76_1_fu_2103_p1;
wire   [15:0] tmp_36_fu_2109_p9;
wire  signed [15:0] tmp_36_fu_2109_p11;
wire   [15:0] tmp_44_fu_2150_p9;
wire   [15:0] tmp_45_fu_2173_p9;
wire  signed [15:0] tmp_45_fu_2173_p11;
wire  signed [25:0] grp_fu_2627_p3;
wire   [9:0] mul_ln76_5_fu_2209_p1;
wire   [15:0] tmp_46_fu_2215_p9;
wire  signed [15:0] tmp_46_fu_2215_p11;
wire  signed [25:0] grp_fu_2644_p3;
wire  signed [26:0] grp_fu_2653_p3;
wire   [8:0] trunc_ln76_fu_2271_p1;
wire   [0:0] tmp_49_fu_2287_p3;
wire   [0:0] icmp_ln76_fu_2274_p2;
wire   [0:0] or_ln76_fu_2294_p2;
wire   [0:0] tmp_47_fu_2264_p3;
wire   [0:0] and_ln76_fu_2300_p2;
wire   [15:0] trunc_ln2_fu_2255_p4;
wire   [15:0] zext_ln76_3_fu_2306_p1;
wire   [15:0] add_ln76_6_fu_2310_p2;
wire   [0:0] tmp_48_fu_2280_p3;
wire   [0:0] tmp_50_fu_2316_p3;
wire   [0:0] xor_ln76_fu_2324_p2;
wire   [0:0] tmp_42_fu_2248_p3;
wire   [0:0] or_ln76_6_fu_2330_p2;
wire   [0:0] xor_ln76_2_fu_2336_p2;
wire   [0:0] xor_ln76_3_fu_2348_p2;
wire   [0:0] or_ln76_1_fu_2354_p2;
wire   [0:0] xor_ln76_1_fu_2342_p2;
wire   [0:0] or_ln76_8_fu_2366_p2;
wire   [0:0] xor_ln76_4_fu_2372_p2;
wire   [0:0] and_ln76_1_fu_2360_p2;
wire   [0:0] and_ln76_2_fu_2378_p2;
wire   [0:0] or_ln76_2_fu_2392_p2;
wire   [15:0] select_ln76_fu_2384_p3;
wire  signed [26:0] grp_fu_2675_p3;
wire   [8:0] trunc_ln76_2_fu_2429_p1;
wire   [0:0] tmp_57_fu_2445_p3;
wire   [0:0] icmp_ln76_1_fu_2432_p2;
wire   [0:0] or_ln76_3_fu_2452_p2;
wire   [0:0] tmp_55_fu_2422_p3;
wire   [0:0] and_ln76_3_fu_2458_p2;
wire   [15:0] trunc_ln76_1_fu_2413_p4;
wire   [15:0] zext_ln76_7_fu_2464_p1;
wire   [15:0] add_ln76_13_fu_2468_p2;
wire   [0:0] tmp_56_fu_2438_p3;
wire   [0:0] tmp_58_fu_2474_p3;
wire   [0:0] xor_ln76_5_fu_2482_p2;
wire   [0:0] tmp_54_fu_2406_p3;
wire   [0:0] or_ln76_7_fu_2488_p2;
wire   [0:0] xor_ln76_6_fu_2494_p2;
wire   [0:0] xor_ln76_8_fu_2506_p2;
wire   [0:0] or_ln76_4_fu_2512_p2;
wire   [0:0] xor_ln76_7_fu_2500_p2;
wire   [0:0] or_ln76_9_fu_2524_p2;
wire   [0:0] xor_ln76_9_fu_2530_p2;
wire   [0:0] and_ln76_4_fu_2518_p2;
wire   [0:0] and_ln76_5_fu_2536_p2;
wire   [0:0] or_ln76_5_fu_2550_p2;
wire   [15:0] select_ln76_2_fu_2542_p3;
wire  signed [15:0] select_ln76_3_fu_2556_p3;
wire  signed [16:0] sext_ln82_fu_2564_p1;
wire  signed [16:0] sext_ln82_1_fu_2567_p1;
wire   [16:0] add_ln82_1_fu_2576_p2;
wire    ap_CS_fsm_state11;
wire   [0:0] xor_ln82_fu_2598_p2;
wire   [0:0] and_ln82_fu_2603_p2;
wire   [0:0] xor_ln82_1_fu_2608_p2;
wire   [15:0] select_ln82_fu_2612_p3;
wire   [7:0] grp_fu_2627_p1;
wire   [9:0] grp_fu_2636_p1;
wire   [7:0] grp_fu_2644_p1;
wire   [7:0] grp_fu_2653_p1;
wire   [9:0] grp_fu_2667_p1;
wire   [7:0] grp_fu_2675_p1;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire   [23:0] grp_fu_2627_p10;
wire   [25:0] grp_fu_2636_p10;
wire   [23:0] grp_fu_2644_p10;
wire   [23:0] grp_fu_2653_p10;
wire   [25:0] grp_fu_2667_p10;
wire   [23:0] grp_fu_2675_p10;
wire   [25:0] mul_ln76_1_fu_2103_p10;
wire   [25:0] mul_ln76_5_fu_2209_p10;
wire  signed [2:0] u_fu_1067_p1;
wire   [2:0] u_fu_1067_p3;
wire   [2:0] u_fu_1067_p5;
wire   [2:0] u_fu_1067_p7;
wire  signed [1:0] k_fu_1341_p1;
wire   [1:0] k_fu_1341_p3;
wire   [1:0] k_fu_1341_p5;
wire  signed [2:0] u_1_fu_1679_p1;
wire   [2:0] u_1_fu_1679_p3;
wire   [2:0] u_1_fu_1679_p5;
wire   [2:0] u_1_fu_1679_p7;
wire  signed [1:0] k_1_fu_1729_p1;
wire   [1:0] k_1_fu_1729_p3;
wire   [1:0] k_1_fu_1729_p5;
wire   [1:0] tmp_33_fu_1903_p1;
wire   [1:0] tmp_33_fu_1903_p3;
wire  signed [1:0] tmp_33_fu_1903_p5;
wire  signed [1:0] tmp_33_fu_1903_p7;
wire  signed [1:0] tmp_34_fu_1961_p1;
wire   [1:0] tmp_34_fu_1961_p3;
wire   [1:0] tmp_34_fu_1961_p5;
wire  signed [1:0] tmp_34_fu_1961_p7;
wire  signed [1:0] tmp_35_fu_1984_p1;
wire  signed [1:0] tmp_35_fu_1984_p3;
wire   [1:0] tmp_35_fu_1984_p5;
wire   [1:0] tmp_35_fu_1984_p7;
wire   [1:0] tmp_43_fu_2070_p1;
wire   [1:0] tmp_43_fu_2070_p3;
wire  signed [1:0] tmp_43_fu_2070_p5;
wire  signed [1:0] tmp_43_fu_2070_p7;
wire   [1:0] tmp_36_fu_2109_p1;
wire  signed [1:0] tmp_36_fu_2109_p3;
wire  signed [1:0] tmp_36_fu_2109_p5;
wire   [1:0] tmp_36_fu_2109_p7;
wire  signed [1:0] tmp_44_fu_2150_p1;
wire   [1:0] tmp_44_fu_2150_p3;
wire   [1:0] tmp_44_fu_2150_p5;
wire  signed [1:0] tmp_44_fu_2150_p7;
wire  signed [1:0] tmp_45_fu_2173_p1;
wire  signed [1:0] tmp_45_fu_2173_p3;
wire   [1:0] tmp_45_fu_2173_p5;
wire   [1:0] tmp_45_fu_2173_p7;
wire   [1:0] tmp_46_fu_2215_p1;
wire  signed [1:0] tmp_46_fu_2215_p3;
wire  signed [1:0] tmp_46_fu_2215_p5;
wire   [1:0] tmp_46_fu_2215_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U42(
    .din0(16'd0),
    .din1(16'd1024),
    .din2(u_fu_1067_p6),
    .din3(u_fu_1067_p8),
    .def(u_fu_1067_p9),
    .sel(u_fu_1067_p10),
    .dout(u_fu_1067_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_7_2_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 3 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 3 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 3 ),
    .def_WIDTH( 3 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 3 ))
sparsemux_7_2_3_1_1_U43(
    .din0(3'd0),
    .din1(3'd4),
    .din2(trunc_ln25_reg_2725),
    .def(k_fu_1341_p7),
    .sel(k_fu_1341_p8),
    .dout(k_fu_1341_p9)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U44(
    .din0(16'd0),
    .din1(16'd1024),
    .din2(u_1_fu_1679_p6),
    .din3(u_1_fu_1679_p8),
    .def(u_1_fu_1679_p9),
    .sel(u_1_fu_1679_p10),
    .dout(u_1_fu_1679_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_7_2_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 3 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 3 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 3 ),
    .def_WIDTH( 3 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 3 ))
sparsemux_7_2_3_1_1_U45(
    .din0(3'd0),
    .din1(3'd4),
    .din2(trunc_ln25_2_reg_2792),
    .def(k_1_fu_1729_p7),
    .sel(k_1_fu_1729_p8),
    .dout(k_1_fu_1729_p9)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U46(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q0),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q0),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q0),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q0),
    .def(tmp_33_fu_1903_p9),
    .sel(trunc_ln19_reg_2779),
    .dout(tmp_33_fu_1903_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U47(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q1),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q1),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q1),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q1),
    .def(tmp_34_fu_1961_p9),
    .sel(trunc_ln19_reg_2779),
    .dout(tmp_34_fu_1961_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h3 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h1 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U48(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q0),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q0),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q0),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q0),
    .def(tmp_35_fu_1984_p9),
    .sel(trunc_ln19_reg_2779),
    .dout(tmp_35_fu_1984_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U49(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q0),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q0),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q0),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q0),
    .def(tmp_43_fu_2070_p9),
    .sel(trunc_ln19_1_reg_2855),
    .dout(tmp_43_fu_2070_p11)
);

eclair_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U50(
    .din0(tmp_34_reg_2993),
    .din1(mul_ln76_1_fu_2103_p1),
    .dout(mul_ln76_1_fu_2103_p2)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U51(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_q0),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_q0),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_q0),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_q0),
    .def(tmp_36_fu_2109_p9),
    .sel(trunc_ln19_reg_2779),
    .dout(tmp_36_fu_2109_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U52(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q1),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q1),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q1),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q1),
    .def(tmp_44_fu_2150_p9),
    .sel(trunc_ln19_1_reg_2855),
    .dout(tmp_44_fu_2150_p11)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h3 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h1 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U53(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q0),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q0),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q0),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q0),
    .def(tmp_45_fu_2173_p9),
    .sel(trunc_ln19_1_reg_2855),
    .dout(tmp_45_fu_2173_p11)
);

eclair_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U54(
    .din0(tmp_44_reg_3108),
    .din1(mul_ln76_5_fu_2209_p1),
    .dout(mul_ln76_5_fu_2209_p2)
);

(* dissolve_hierarchy = "yes" *) eclair_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U55(
    .din0(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_q0),
    .din1(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_q0),
    .din2(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_q0),
    .din3(p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_q0),
    .def(tmp_46_fu_2215_p9),
    .sel(trunc_ln19_1_reg_2855),
    .dout(tmp_46_fu_2215_p11)
);

eclair_mac_muladd_16s_8ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_8ns_26s_26_4_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_33_fu_1903_p11),
    .din1(grp_fu_2627_p1),
    .din2(mul_ln76_1_fu_2103_p2),
    .ce(1'b1),
    .dout(grp_fu_2627_p3)
);

eclair_mac_muladd_16s_10ns_26s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_10ns_26s_27_4_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_35_fu_1984_p11),
    .din1(grp_fu_2636_p1),
    .din2(grp_fu_2627_p3),
    .ce(1'b1),
    .dout(grp_fu_2636_p3)
);

eclair_mac_muladd_16s_8ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_8ns_26s_26_4_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_43_fu_2070_p11),
    .din1(grp_fu_2644_p1),
    .din2(mul_ln76_5_fu_2209_p2),
    .ce(1'b1),
    .dout(grp_fu_2644_p3)
);

eclair_mac_muladd_16s_8ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_8ns_27s_27_4_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_36_fu_2109_p11),
    .din1(grp_fu_2653_p1),
    .din2(grp_fu_2636_p3),
    .ce(1'b1),
    .dout(grp_fu_2653_p3)
);

eclair_mac_muladd_16s_10ns_26s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_10ns_26s_27_4_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_45_fu_2173_p11),
    .din1(grp_fu_2667_p1),
    .din2(grp_fu_2644_p3),
    .ce(1'b1),
    .dout(grp_fu_2667_p3)
);

eclair_mac_muladd_16s_8ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_8ns_27s_27_4_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_46_fu_2215_p11),
    .din1(grp_fu_2675_p1),
    .din2(grp_fu_2667_p3),
    .ce(1'b1),
    .dout(grp_fu_2675_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        and_ln12_11_reg_2761 <= and_ln12_11_fu_1317_p2;
        and_ln12_8_reg_2751 <= and_ln12_8_fu_1219_p2;
        and_ln19_reg_2730 <= and_ln19_fu_1033_p2;
        icmp_ln12_6_reg_2756 <= icmp_ln12_6_fu_1259_p2;
        t_4_reg_2746 <= t_4_fu_1199_p2;
        tmp_10_reg_2720 <= t_2_fu_876_p3[32'd15];
        tmp_19_reg_2741 <= add_ln12_4_fu_1125_p2[32'd28];
        trunc_ln25_reg_2725 <= trunc_ln25_fu_939_p1;
        u_reg_2735 <= u_fu_1067_p11;
        xor_ln12_11_reg_2767 <= xor_ln12_11_fu_1329_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln12_1_reg_2699 <= and_ln12_1_fu_728_p2;
        and_ln12_4_reg_2709 <= and_ln12_4_fu_826_p2;
        icmp_ln12_2_reg_2704 <= icmp_ln12_2_fu_768_p2;
        t_1_reg_2694 <= t_1_fu_708_p2;
        tmp_2_reg_2689 <= add_ln12_1_fu_634_p2[32'd28];
        xor_ln12_5_reg_2715 <= xor_ln12_5_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        and_ln19_1_reg_2797 <= and_ln19_1_fu_1645_p2;
        k_reg_2772 <= k_fu_1341_p9;
        tmp_27_reg_2787 <= t_5_fu_1488_p3[32'd15];
        trunc_ln19_reg_2779 <= trunc_ln19_fu_1360_p1;
        trunc_ln25_2_reg_2792 <= trunc_ln25_2_fu_1551_p1;
        u_1_reg_2802 <= u_1_fu_1679_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        b1_1_reg_3003 <= LUT_B1_q0;
        b3_1_reg_3008 <= LUT_B3_q0;
        tmp_34_reg_2993 <= tmp_34_fu_1961_p11;
        tmp_53_reg_3058 <= add_ln76_9_fu_2057_p2[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b1_reg_2863 <= LUT_B1_q0;
        b3_reg_2868 <= LUT_B3_q0;
        k_1_reg_2848 <= k_1_fu_1729_p9;
        tmp_41_reg_2918 <= add_ln76_2_fu_1890_p2[32'd2];
        trunc_ln19_1_reg_2855 <= trunc_ln19_1_fu_1748_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        o_sum_1_reg_3159 <= o_sum_1_fu_2571_p2;
        tmp_59_reg_3164 <= add_ln82_1_fu_2576_p2[32'd16];
        tmp_60_reg_3170 <= o_sum_1_fu_2571_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        o_sum_reg_3148 <= o_sum_fu_2398_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_596 <= LUT_B2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_44_reg_3108 <= tmp_44_fu_2150_p11;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        LUT_B0_address0_local = zext_ln70_1_fu_1942_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LUT_B0_address0_local = zext_ln70_fu_1715_p1;
    end else begin
        LUT_B0_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        LUT_B0_ce0_local = 1'b1;
    end else begin
        LUT_B0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        LUT_B1_address0_local = zext_ln70_1_fu_1942_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LUT_B1_address0_local = zext_ln70_fu_1715_p1;
    end else begin
        LUT_B1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        LUT_B1_ce0_local = 1'b1;
    end else begin
        LUT_B1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        LUT_B2_address0_local = zext_ln70_1_fu_1942_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LUT_B2_address0_local = zext_ln70_fu_1715_p1;
    end else begin
        LUT_B2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        LUT_B2_ce0_local = 1'b1;
    end else begin
        LUT_B2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        LUT_B3_address0_local = zext_ln70_1_fu_1942_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LUT_B3_address0_local = zext_ln70_fu_1715_p1;
    end else begin
        LUT_B3_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        LUT_B3_ce0_local = 1'b1;
    end else begin
        LUT_B3_ce0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0_ap_vld = 1'b1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1_ap_vld = 1'b1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0_ap_vld = 1'b1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1_ap_vld = 1'b1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0_local = zext_ln76_2_fu_1954_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0_local = zext_ln76_1_fu_1882_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0_local = zext_ln47_fu_1372_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0_local = zext_ln76_2_fu_1954_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0_local = zext_ln76_1_fu_1882_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0_local = zext_ln47_fu_1372_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0_local = zext_ln76_2_fu_1954_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0_local = zext_ln76_1_fu_1882_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0_local = zext_ln47_fu_1372_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0_local = zext_ln76_2_fu_1954_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0_local = zext_ln76_1_fu_1882_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0_local = zext_ln47_fu_1372_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0_local = zext_ln76_6_fu_2143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0_local = zext_ln76_5_fu_2049_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0_local = zext_ln47_1_fu_1760_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0_local = zext_ln76_6_fu_2143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0_local = zext_ln76_5_fu_2049_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0_local = zext_ln47_1_fu_1760_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0_local = zext_ln76_6_fu_2143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0_local = zext_ln76_5_fu_2049_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0_local = zext_ln47_1_fu_1760_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0_local = zext_ln76_6_fu_2143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0_local = zext_ln76_5_fu_2049_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0_local = zext_ln47_1_fu_1760_p1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1_local = 1'b1;
    end else begin
        p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LUT_B0_address0 = LUT_B0_address0_local;

assign LUT_B0_ce0 = LUT_B0_ce0_local;

assign LUT_B1_address0 = LUT_B1_address0_local;

assign LUT_B1_ce0 = LUT_B1_ce0_local;

assign LUT_B2_address0 = LUT_B2_address0_local;

assign LUT_B2_ce0 = LUT_B2_ce0_local;

assign LUT_B3_address0 = LUT_B3_address0_local;

assign LUT_B3_ce0 = LUT_B3_ce0_local;

assign add_ln12_1_fu_634_p2 = ($signed(sext_ln12_1_fu_618_p1) + $signed(sext_ln12_3_fu_630_p1));

assign add_ln12_2_fu_1095_p2 = ($signed(sext_ln12_2_fu_1091_p1) + $signed(17'd2048));

assign add_ln12_4_fu_1125_p2 = ($signed(sext_ln12_4_fu_1109_p1) + $signed(sext_ln12_5_fu_1121_p1));

assign add_ln12_fu_604_p2 = ($signed(sext_ln12_fu_600_p1) + $signed(17'd2048));

assign add_ln24_1_fu_1529_p2 = (tmp_28_fu_1509_p4 + 6'd1);

assign add_ln24_fu_917_p2 = (tmp_s_fu_897_p4 + 6'd1);

assign add_ln49_1_fu_1434_p2 = (tmp_14_cast1_fu_1406_p4 + 8'd1);

assign add_ln49_2_fu_1788_p2 = (sub_ln49_1_fu_1782_p2 + 32'd524288);

assign add_ln49_3_fu_1822_p2 = (tmp_32_cast1_fu_1794_p4 + 8'd1);

assign add_ln49_fu_1400_p2 = (sub_ln49_fu_1394_p2 + 32'd524288);

assign add_ln76_13_fu_2468_p2 = (trunc_ln76_1_fu_2413_p4 + zext_ln76_7_fu_2464_p1);

assign add_ln76_1_fu_1869_p2 = (k_reg_2772 + 3'd2);

assign add_ln76_2_fu_1890_p2 = (k_reg_2772 + 3'd3);

assign add_ln76_6_fu_2310_p2 = (trunc_ln2_fu_2255_p4 + zext_ln76_3_fu_2306_p1);

assign add_ln76_7_fu_2015_p2 = (k_1_reg_2848 + 3'd1);

assign add_ln76_8_fu_2036_p2 = (k_1_reg_2848 + 3'd2);

assign add_ln76_9_fu_2057_p2 = (k_1_reg_2848 + 3'd3);

assign add_ln76_fu_1848_p2 = (k_reg_2772 + 3'd1);

assign add_ln82_1_fu_2576_p2 = ($signed(sext_ln82_fu_2564_p1) + $signed(sext_ln82_1_fu_2567_p1));

assign and_ln12_10_fu_1456_p2 = (icmp_ln12_6_reg_2756 & and_ln12_8_reg_2751);

assign and_ln12_11_fu_1317_p2 = (xor_ln12_10_fu_1311_p2 & or_ln12_4_fu_1305_p2);

assign and_ln12_12_fu_1323_p2 = (tmp_25_fu_1205_p3 & select_ln12_5_fu_1291_p3);

assign and_ln12_13_fu_1471_p2 = (xor_ln12_11_reg_2767 & empty_14_fu_1466_p2);

assign and_ln12_1_fu_728_p2 = (xor_ln12_fu_722_p2 & tmp_4_fu_676_p3);

assign and_ln12_2_fu_794_p2 = (xor_ln12_1_fu_788_p2 & icmp_ln12_1_fu_752_p2);

assign and_ln12_3_fu_844_p2 = (icmp_ln12_2_reg_2704 & and_ln12_1_reg_2699);

assign and_ln12_4_fu_826_p2 = (xor_ln12_4_fu_820_p2 & or_ln12_1_fu_814_p2);

assign and_ln12_5_fu_832_p2 = (tmp_6_fu_714_p3 & select_ln12_1_fu_800_p3);

assign and_ln12_6_fu_859_p2 = (xor_ln12_5_reg_2715 & empty_fu_854_p2);

assign and_ln12_7_fu_1189_p2 = (tmp_20_fu_1149_p3 & or_ln12_3_fu_1183_p2);

assign and_ln12_8_fu_1219_p2 = (xor_ln12_6_fu_1213_p2 & tmp_21_fu_1167_p3);

assign and_ln12_9_fu_1285_p2 = (xor_ln12_7_fu_1279_p2 & icmp_ln12_5_fu_1243_p2);

assign and_ln12_fu_698_p2 = (tmp_3_fu_658_p3 & or_ln12_fu_692_p2);

assign and_ln19_1_fu_1645_p2 = (xor_ln15_1_fu_1639_p2 & icmp_ln19_1_fu_1503_p2);

assign and_ln19_fu_1033_p2 = (xor_ln15_fu_1027_p2 & icmp_ln19_fu_891_p2);

assign and_ln25_1_fu_1619_p2 = (xor_ln25_2_fu_1613_p2 & tmp_31_fu_1605_p3);

assign and_ln25_2_fu_1051_p2 = (xor_ln25_1_fu_1013_p2 & xor_ln19_fu_1045_p2);

assign and_ln25_3_fu_1663_p2 = (xor_ln25_3_fu_1625_p2 & xor_ln19_1_fu_1657_p2);

assign and_ln25_fu_1007_p2 = (xor_ln25_fu_1001_p2 & tmp_13_fu_993_p3);

assign and_ln76_1_fu_2360_p2 = (xor_ln76_1_fu_2342_p2 & or_ln76_1_fu_2354_p2);

assign and_ln76_2_fu_2378_p2 = (xor_ln76_4_fu_2372_p2 & tmp_42_fu_2248_p3);

assign and_ln76_3_fu_2458_p2 = (tmp_55_fu_2422_p3 & or_ln76_3_fu_2452_p2);

assign and_ln76_4_fu_2518_p2 = (xor_ln76_7_fu_2500_p2 & or_ln76_4_fu_2512_p2);

assign and_ln76_5_fu_2536_p2 = (xor_ln76_9_fu_2530_p2 & tmp_54_fu_2406_p3);

assign and_ln76_fu_2300_p2 = (tmp_47_fu_2264_p3 & or_ln76_fu_2294_p2);

assign and_ln82_fu_2603_p2 = (xor_ln82_fu_2598_p2 & tmp_60_reg_3170);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = ((xor_ln82_1_fu_2608_p2[0:0] == 1'b1) ? select_ln82_fu_2612_p3 : o_sum_1_reg_3159);

assign eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_0 = k_fu_1341_p9;

assign eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_61_1 = k_1_fu_1729_p9;

assign eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_0 = ui_fu_1448_p3;

assign eclair_ap_fixed_const_ap_fixed_ap_fixed_const_C_u_index_60_1 = ui_1_fu_1836_p3;

assign empty_14_fu_1466_p2 = (xor_ln12_8_fu_1460_p2 & tmp_19_reg_2741);

assign empty_fu_854_p2 = (xor_ln12_2_fu_848_p2 & tmp_2_reg_2689);

assign grp_fu_2627_p1 = grp_fu_2627_p10;

assign grp_fu_2627_p10 = LUT_B0_q0;

assign grp_fu_2636_p1 = grp_fu_2636_p10;

assign grp_fu_2636_p10 = reg_596;

assign grp_fu_2644_p1 = grp_fu_2644_p10;

assign grp_fu_2644_p10 = LUT_B0_q0;

assign grp_fu_2653_p1 = grp_fu_2653_p10;

assign grp_fu_2653_p10 = b3_reg_2868;

assign grp_fu_2667_p1 = grp_fu_2667_p10;

assign grp_fu_2667_p10 = reg_596;

assign grp_fu_2675_p1 = grp_fu_2675_p10;

assign grp_fu_2675_p10 = b3_1_reg_3008;

assign icmp_ln12_1_fu_752_p2 = ((tmp_7_fu_742_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln12_2_fu_768_p2 = ((tmp_8_fu_758_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln12_3_fu_774_p2 = ((tmp_8_fu_758_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_4_fu_1161_p2 = ((trunc_ln12_1_fu_1157_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_5_fu_1243_p2 = ((tmp_23_fu_1233_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln12_6_fu_1259_p2 = ((tmp_24_fu_1249_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln12_7_fu_1265_p2 = ((tmp_24_fu_1249_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_670_p2 = ((trunc_ln12_fu_666_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_1_fu_1503_p2 = (($signed(t_5_fu_1488_p3) > $signed(16'd5119)) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_891_p2 = (($signed(t_2_fu_876_p3) > $signed(16'd5119)) ? 1'b1 : 1'b0);

assign icmp_ln24_1_fu_1523_p2 = ((trunc_ln24_1_fu_1519_p1 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_911_p2 = ((trunc_ln24_fu_907_p1 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_1_fu_1816_p2 = ((trunc_ln49_1_fu_1812_p1 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_1428_p2 = ((trunc_ln49_fu_1424_p1 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln76_1_fu_2432_p2 = ((trunc_ln76_2_fu_2429_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_2274_p2 = ((trunc_ln76_fu_2271_p1 != 9'd0) ? 1'b1 : 1'b0);

assign k_1_fu_1729_p7 = 'bx;

assign k_1_fu_1729_p8 = {{tmp_27_reg_2787}, {and_ln19_1_reg_2797}};

assign k_fu_1341_p7 = 'bx;

assign k_fu_1341_p8 = {{tmp_10_reg_2720}, {and_ln19_reg_2730}};

assign mul_ln76_1_fu_2103_p1 = mul_ln76_1_fu_2103_p10;

assign mul_ln76_1_fu_2103_p10 = b1_reg_2863;

assign mul_ln76_5_fu_2209_p1 = mul_ln76_5_fu_2209_p10;

assign mul_ln76_5_fu_2209_p10 = b1_1_reg_3003;

assign o_sum_1_fu_2571_p2 = ($signed(o_sum_reg_3148) + $signed(select_ln76_3_fu_2556_p3));

assign o_sum_fu_2398_p3 = ((or_ln76_2_fu_2392_p2[0:0] == 1'b1) ? select_ln76_fu_2384_p3 : add_ln76_6_fu_2310_p2);

assign or_ln12_1_fu_814_p2 = (xor_ln12_3_fu_808_p2 | tmp_6_fu_714_p3);

assign or_ln12_2_fu_871_p2 = (and_ln12_6_fu_859_p2 | and_ln12_4_reg_2709);

assign or_ln12_3_fu_1183_p2 = (tmp_22_fu_1175_p3 | icmp_ln12_4_fu_1161_p2);

assign or_ln12_4_fu_1305_p2 = (xor_ln12_9_fu_1299_p2 | tmp_25_fu_1205_p3);

assign or_ln12_5_fu_1483_p2 = (and_ln12_13_fu_1471_p2 | and_ln12_11_reg_2761);

assign or_ln12_fu_692_p2 = (tmp_5_fu_684_p3 | icmp_ln12_fu_670_p2);

assign or_ln19_1_fu_1651_p2 = (tmp_27_fu_1495_p3 | icmp_ln19_1_fu_1503_p2);

assign or_ln19_fu_1039_p2 = (tmp_10_fu_883_p3 | icmp_ln19_fu_891_p2);

assign or_ln76_1_fu_2354_p2 = (xor_ln76_3_fu_2348_p2 | tmp_50_fu_2316_p3);

assign or_ln76_2_fu_2392_p2 = (and_ln76_2_fu_2378_p2 | and_ln76_1_fu_2360_p2);

assign or_ln76_3_fu_2452_p2 = (tmp_57_fu_2445_p3 | icmp_ln76_1_fu_2432_p2);

assign or_ln76_4_fu_2512_p2 = (xor_ln76_8_fu_2506_p2 | tmp_58_fu_2474_p3);

assign or_ln76_5_fu_2550_p2 = (and_ln76_5_fu_2536_p2 | and_ln76_4_fu_2518_p2);

assign or_ln76_6_fu_2330_p2 = (xor_ln76_fu_2324_p2 | tmp_50_fu_2316_p3);

assign or_ln76_7_fu_2488_p2 = (xor_ln76_5_fu_2482_p2 | tmp_58_fu_2474_p3);

assign or_ln76_8_fu_2366_p2 = (tmp_50_fu_2316_p3 | tmp_48_fu_2280_p3);

assign or_ln76_9_fu_2524_p2 = (tmp_58_fu_2474_p3 | tmp_56_fu_2438_p3);

assign or_ln76_fu_2294_p2 = (tmp_49_fu_2287_p3 | icmp_ln76_fu_2274_p2);

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_address1 = zext_ln76_fu_1861_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_0_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_address1 = zext_ln76_fu_1861_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_1_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_address1 = zext_ln76_fu_1861_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_2_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_address1 = zext_ln76_fu_1861_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_0_3_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_address1 = zext_ln76_4_fu_2028_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_0_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_address1 = zext_ln76_4_fu_2028_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_1_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_address1 = zext_ln76_4_fu_2028_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_2_ce1_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_address1 = zext_ln76_4_fu_2028_p1;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce0_local;

assign p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1 = p_ZZ6eclairPK8ap_fixedILi16ELi6EL9ap_q_mode4EL9ap_o_mode0ELi0EEPS2_S4_E1P_1_3_ce1_local;

assign ref_tmp_i_i_i_0_1_fu_1543_p3 = ((tmp_27_fu_1495_p3[0:0] == 1'b1) ? select_ln24_1_fu_1535_p3 : tmp_28_fu_1509_p4);

assign ref_tmp_i_i_i_0_fu_931_p3 = ((tmp_10_fu_883_p3[0:0] == 1'b1) ? select_ln24_fu_923_p3 : tmp_s_fu_897_p4);

assign select_ln12_1_fu_800_p3 = ((and_ln12_1_fu_728_p2[0:0] == 1'b1) ? and_ln12_2_fu_794_p2 : icmp_ln12_2_fu_768_p2);

assign select_ln12_2_fu_864_p3 = ((and_ln12_4_reg_2709[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln12_4_fu_1271_p3 = ((and_ln12_8_fu_1219_p2[0:0] == 1'b1) ? icmp_ln12_6_fu_1259_p2 : icmp_ln12_7_fu_1265_p2);

assign select_ln12_5_fu_1291_p3 = ((and_ln12_8_fu_1219_p2[0:0] == 1'b1) ? and_ln12_9_fu_1285_p2 : icmp_ln12_6_fu_1259_p2);

assign select_ln12_6_fu_1476_p3 = ((and_ln12_11_reg_2761[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln12_fu_780_p3 = ((and_ln12_1_fu_728_p2[0:0] == 1'b1) ? icmp_ln12_2_fu_768_p2 : icmp_ln12_3_fu_774_p2);

assign select_ln24_1_fu_1535_p3 = ((icmp_ln24_1_fu_1523_p2[0:0] == 1'b1) ? add_ln24_1_fu_1529_p2 : tmp_28_fu_1509_p4);

assign select_ln24_fu_923_p3 = ((icmp_ln24_fu_911_p2[0:0] == 1'b1) ? add_ln24_fu_917_p2 : tmp_s_fu_897_p4);

assign select_ln25_2_fu_1571_p3 = ((tmp_29_fu_1555_p3[0:0] == 1'b1) ? 16'd32768 : shl_ln25_1_fu_1563_p3);

assign select_ln25_fu_959_p3 = ((tmp_11_fu_943_p3[0:0] == 1'b1) ? 16'd32768 : shl_ln_fu_951_p3);

assign select_ln49_1_fu_1828_p3 = ((icmp_ln49_1_fu_1816_p2[0:0] == 1'b1) ? add_ln49_3_fu_1822_p2 : tmp_32_cast1_fu_1794_p4);

assign select_ln49_fu_1440_p3 = ((icmp_ln49_fu_1428_p2[0:0] == 1'b1) ? add_ln49_1_fu_1434_p2 : tmp_14_cast1_fu_1406_p4);

assign select_ln76_2_fu_2542_p3 = ((and_ln76_4_fu_2518_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln76_3_fu_2556_p3 = ((or_ln76_5_fu_2550_p2[0:0] == 1'b1) ? select_ln76_2_fu_2542_p3 : add_ln76_13_fu_2468_p2);

assign select_ln76_fu_2384_p3 = ((and_ln76_1_fu_2360_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln82_fu_2612_p3 = ((and_ln82_fu_2603_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln12_1_fu_618_p1 = $signed(tmp_fu_610_p3);

assign sext_ln12_2_fu_1091_p1 = $signed(x_1_val);

assign sext_ln12_3_fu_630_p1 = $signed(tmp_1_fu_622_p3);

assign sext_ln12_4_fu_1109_p1 = $signed(tmp_17_fu_1101_p3);

assign sext_ln12_5_fu_1121_p1 = $signed(tmp_18_fu_1113_p3);

assign sext_ln12_fu_600_p1 = $signed(x_0_val);

assign sext_ln49_1_fu_1768_p1 = u_1_reg_2802;

assign sext_ln49_2_fu_1390_p1 = $signed(tmp_15_fu_1383_p3);

assign sext_ln49_3_fu_1778_p1 = $signed(tmp_37_fu_1771_p3);

assign sext_ln49_fu_1380_p1 = u_reg_2735;

assign sext_ln82_1_fu_2567_p1 = select_ln76_3_fu_2556_p3;

assign sext_ln82_fu_2564_p1 = o_sum_reg_3148;

assign shl_ln25_1_fu_1563_p3 = {{ref_tmp_i_i_i_0_1_fu_1543_p3}, {10'd0}};

assign shl_ln_fu_951_p3 = {{ref_tmp_i_i_i_0_fu_931_p3}, {10'd0}};

assign sub_ln25_1_fu_1587_p2 = (zext_ln25_2_fu_1579_p1 - zext_ln25_3_fu_1583_p1);

assign sub_ln25_fu_975_p2 = (zext_ln25_fu_967_p1 - zext_ln25_1_fu_971_p1);

assign sub_ln49_1_fu_1782_p2 = ($signed(sext_ln49_3_fu_1778_p1) - $signed(sext_ln49_1_fu_1768_p1));

assign sub_ln49_fu_1394_p2 = ($signed(sext_ln49_2_fu_1390_p1) - $signed(sext_ln49_fu_1380_p1));

assign t_1_fu_708_p2 = (t_fu_648_p4 + zext_ln12_fu_704_p1);

assign t_2_fu_876_p3 = ((or_ln12_2_fu_871_p2[0:0] == 1'b1) ? select_ln12_2_fu_864_p3 : t_1_reg_2694);

assign t_3_fu_1139_p4 = {{add_ln12_4_fu_1125_p2[25:10]}};

assign t_4_fu_1199_p2 = (t_3_fu_1139_p4 + zext_ln12_1_fu_1195_p1);

assign t_5_fu_1488_p3 = ((or_ln12_5_fu_1483_p2[0:0] == 1'b1) ? select_ln12_6_fu_1476_p3 : t_4_reg_2746);

assign t_fu_648_p4 = {{add_ln12_1_fu_634_p2[25:10]}};

assign tmp_10_fu_883_p3 = t_2_fu_876_p3[32'd15];

assign tmp_11_fu_943_p3 = ref_tmp_i_i_i_0_fu_931_p3[32'd5];

assign tmp_12_fu_981_p3 = sub_ln25_fu_975_p2[32'd16];

assign tmp_13_fu_993_p3 = sub_ln25_fu_975_p2[32'd15];

assign tmp_14_cast1_fu_1406_p4 = {{add_ln49_fu_1400_p2[27:20]}};

assign tmp_14_fu_1364_p3 = k_fu_1341_p9[32'd2];

assign tmp_15_fu_1383_p3 = {{u_reg_2735}, {15'd0}};

assign tmp_16_fu_1416_p3 = add_ln49_fu_1400_p2[32'd31];

assign tmp_17_fu_1101_p3 = {{add_ln12_2_fu_1095_p2}, {10'd0}};

assign tmp_18_fu_1113_p3 = {{add_ln12_2_fu_1095_p2}, {8'd0}};

assign tmp_19_fu_1131_p3 = add_ln12_4_fu_1125_p2[32'd28];

assign tmp_1_fu_622_p3 = {{add_ln12_fu_604_p2}, {8'd0}};

assign tmp_20_fu_1149_p3 = add_ln12_4_fu_1125_p2[32'd9];

assign tmp_21_fu_1167_p3 = add_ln12_4_fu_1125_p2[32'd25];

assign tmp_22_fu_1175_p3 = add_ln12_4_fu_1125_p2[32'd10];

assign tmp_23_fu_1233_p4 = {{add_ln12_4_fu_1125_p2[28:27]}};

assign tmp_24_fu_1249_p4 = {{add_ln12_4_fu_1125_p2[28:26]}};

assign tmp_25_fu_1205_p3 = t_4_fu_1199_p2[32'd15];

assign tmp_26_fu_1225_p3 = add_ln12_4_fu_1125_p2[32'd26];

assign tmp_27_fu_1495_p3 = t_5_fu_1488_p3[32'd15];

assign tmp_28_fu_1509_p4 = {{t_5_fu_1488_p3[15:10]}};

assign tmp_29_fu_1555_p3 = ref_tmp_i_i_i_0_1_fu_1543_p3[32'd5];

assign tmp_2_fu_640_p3 = add_ln12_1_fu_634_p2[32'd28];

assign tmp_30_fu_1593_p3 = sub_ln25_1_fu_1587_p2[32'd16];

assign tmp_31_fu_1605_p3 = sub_ln25_1_fu_1587_p2[32'd15];

assign tmp_32_cast1_fu_1794_p4 = {{add_ln49_2_fu_1788_p2[27:20]}};

assign tmp_32_fu_1752_p3 = k_1_fu_1729_p9[32'd2];

assign tmp_33_fu_1903_p9 = 'bx;

assign tmp_34_fu_1961_p9 = 'bx;

assign tmp_35_fu_1984_p9 = 'bx;

assign tmp_36_fu_2109_p9 = 'bx;

assign tmp_37_fu_1771_p3 = {{u_1_reg_2802}, {15'd0}};

assign tmp_38_fu_1804_p3 = add_ln49_2_fu_1788_p2[32'd31];

assign tmp_39_fu_1853_p3 = add_ln76_fu_1848_p2[32'd2];

assign tmp_3_fu_658_p3 = add_ln12_1_fu_634_p2[32'd9];

assign tmp_40_fu_1874_p3 = add_ln76_1_fu_1869_p2[32'd2];

assign tmp_42_fu_2248_p3 = grp_fu_2653_p3[32'd26];

assign tmp_43_fu_2070_p9 = 'bx;

assign tmp_44_fu_2150_p9 = 'bx;

assign tmp_45_fu_2173_p9 = 'bx;

assign tmp_46_fu_2215_p9 = 'bx;

assign tmp_47_fu_2264_p3 = grp_fu_2653_p3[32'd9];

assign tmp_48_fu_2280_p3 = grp_fu_2653_p3[32'd25];

assign tmp_49_fu_2287_p3 = grp_fu_2653_p3[32'd10];

assign tmp_4_fu_676_p3 = add_ln12_1_fu_634_p2[32'd25];

assign tmp_50_fu_2316_p3 = add_ln76_6_fu_2310_p2[32'd15];

assign tmp_51_fu_2020_p3 = add_ln76_7_fu_2015_p2[32'd2];

assign tmp_52_fu_2041_p3 = add_ln76_8_fu_2036_p2[32'd2];

assign tmp_54_fu_2406_p3 = grp_fu_2675_p3[32'd26];

assign tmp_55_fu_2422_p3 = grp_fu_2675_p3[32'd9];

assign tmp_56_fu_2438_p3 = grp_fu_2675_p3[32'd25];

assign tmp_57_fu_2445_p3 = grp_fu_2675_p3[32'd10];

assign tmp_58_fu_2474_p3 = add_ln76_13_fu_2468_p2[32'd15];

assign tmp_5_fu_684_p3 = add_ln12_1_fu_634_p2[32'd10];

assign tmp_6_fu_714_p3 = t_1_fu_708_p2[32'd15];

assign tmp_7_fu_742_p4 = {{add_ln12_1_fu_634_p2[28:27]}};

assign tmp_8_fu_758_p4 = {{add_ln12_1_fu_634_p2[28:26]}};

assign tmp_9_fu_734_p3 = add_ln12_1_fu_634_p2[32'd26];

assign tmp_fu_610_p3 = {{add_ln12_fu_604_p2}, {10'd0}};

assign tmp_s_fu_897_p4 = {{t_2_fu_876_p3[15:10]}};

assign trunc_ln12_1_fu_1157_p1 = add_ln12_4_fu_1125_p2[8:0];

assign trunc_ln12_fu_666_p1 = add_ln12_1_fu_634_p2[8:0];

assign trunc_ln19_1_fu_1748_p1 = k_1_fu_1729_p9[1:0];

assign trunc_ln19_fu_1360_p1 = k_fu_1341_p9[1:0];

assign trunc_ln24_1_fu_1519_p1 = t_5_fu_1488_p3[9:0];

assign trunc_ln24_fu_907_p1 = t_2_fu_876_p3[9:0];

assign trunc_ln25_2_fu_1551_p1 = ref_tmp_i_i_i_0_1_fu_1543_p3[2:0];

assign trunc_ln25_fu_939_p1 = ref_tmp_i_i_i_0_fu_931_p3[2:0];

assign trunc_ln2_fu_2255_p4 = {{grp_fu_2653_p3[25:10]}};

assign trunc_ln49_1_fu_1812_p1 = add_ln49_2_fu_1788_p2[19:0];

assign trunc_ln49_fu_1424_p1 = add_ln49_fu_1400_p2[19:0];

assign trunc_ln76_1_fu_2413_p4 = {{grp_fu_2675_p3[25:10]}};

assign trunc_ln76_2_fu_2429_p1 = grp_fu_2675_p3[8:0];

assign trunc_ln76_fu_2271_p1 = grp_fu_2653_p3[8:0];

assign u_1_fu_1679_p10 = {{{tmp_27_fu_1495_p3}, {and_ln19_1_fu_1645_p2}}, {and_ln25_3_fu_1663_p2}};

assign u_1_fu_1679_p6 = ((and_ln25_1_fu_1619_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign u_1_fu_1679_p8 = sub_ln25_1_fu_1587_p2[15:0];

assign u_1_fu_1679_p9 = 'bx;

assign u_fu_1067_p10 = {{{tmp_10_fu_883_p3}, {and_ln19_fu_1033_p2}}, {and_ln25_2_fu_1051_p2}};

assign u_fu_1067_p6 = ((and_ln25_fu_1007_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign u_fu_1067_p8 = sub_ln25_fu_975_p2[15:0];

assign u_fu_1067_p9 = 'bx;

assign ui_1_fu_1836_p3 = ((tmp_38_fu_1804_p3[0:0] == 1'b1) ? select_ln49_1_fu_1828_p3 : tmp_32_cast1_fu_1794_p4);

assign ui_fu_1448_p3 = ((tmp_16_fu_1416_p3[0:0] == 1'b1) ? select_ln49_fu_1440_p3 : tmp_14_cast1_fu_1406_p4);

assign xor_ln12_10_fu_1311_p2 = (tmp_19_fu_1131_p3 ^ 1'd1);

assign xor_ln12_11_fu_1329_p2 = (1'd1 ^ and_ln12_12_fu_1323_p2);

assign xor_ln12_1_fu_788_p2 = (tmp_9_fu_734_p3 ^ 1'd1);

assign xor_ln12_2_fu_848_p2 = (1'd1 ^ and_ln12_3_fu_844_p2);

assign xor_ln12_3_fu_808_p2 = (select_ln12_fu_780_p3 ^ 1'd1);

assign xor_ln12_4_fu_820_p2 = (tmp_2_fu_640_p3 ^ 1'd1);

assign xor_ln12_5_fu_838_p2 = (1'd1 ^ and_ln12_5_fu_832_p2);

assign xor_ln12_6_fu_1213_p2 = (tmp_25_fu_1205_p3 ^ 1'd1);

assign xor_ln12_7_fu_1279_p2 = (tmp_26_fu_1225_p3 ^ 1'd1);

assign xor_ln12_8_fu_1460_p2 = (1'd1 ^ and_ln12_10_fu_1456_p2);

assign xor_ln12_9_fu_1299_p2 = (select_ln12_4_fu_1271_p3 ^ 1'd1);

assign xor_ln12_fu_722_p2 = (tmp_6_fu_714_p3 ^ 1'd1);

assign xor_ln15_1_fu_1639_p2 = (tmp_27_fu_1495_p3 ^ 1'd1);

assign xor_ln15_fu_1027_p2 = (tmp_10_fu_883_p3 ^ 1'd1);

assign xor_ln19_1_fu_1657_p2 = (or_ln19_1_fu_1651_p2 ^ 1'd1);

assign xor_ln19_fu_1045_p2 = (or_ln19_fu_1039_p2 ^ 1'd1);

assign xor_ln25_1_fu_1013_p2 = (tmp_13_fu_993_p3 ^ tmp_12_fu_981_p3);

assign xor_ln25_2_fu_1613_p2 = (tmp_30_fu_1593_p3 ^ 1'd1);

assign xor_ln25_3_fu_1625_p2 = (tmp_31_fu_1605_p3 ^ tmp_30_fu_1593_p3);

assign xor_ln25_fu_1001_p2 = (tmp_12_fu_981_p3 ^ 1'd1);

assign xor_ln76_1_fu_2342_p2 = (tmp_42_fu_2248_p3 ^ 1'd1);

assign xor_ln76_2_fu_2336_p2 = (tmp_42_fu_2248_p3 ^ or_ln76_6_fu_2330_p2);

assign xor_ln76_3_fu_2348_p2 = (xor_ln76_2_fu_2336_p2 ^ 1'd1);

assign xor_ln76_4_fu_2372_p2 = (or_ln76_8_fu_2366_p2 ^ 1'd1);

assign xor_ln76_5_fu_2482_p2 = (tmp_56_fu_2438_p3 ^ 1'd1);

assign xor_ln76_6_fu_2494_p2 = (tmp_54_fu_2406_p3 ^ or_ln76_7_fu_2488_p2);

assign xor_ln76_7_fu_2500_p2 = (tmp_54_fu_2406_p3 ^ 1'd1);

assign xor_ln76_8_fu_2506_p2 = (xor_ln76_6_fu_2494_p2 ^ 1'd1);

assign xor_ln76_9_fu_2530_p2 = (or_ln76_9_fu_2524_p2 ^ 1'd1);

assign xor_ln76_fu_2324_p2 = (tmp_48_fu_2280_p3 ^ 1'd1);

assign xor_ln82_1_fu_2608_p2 = (tmp_60_reg_3170 ^ tmp_59_reg_3164);

assign xor_ln82_fu_2598_p2 = (tmp_59_reg_3164 ^ 1'd1);

assign zext_ln12_1_fu_1195_p1 = and_ln12_7_fu_1189_p2;

assign zext_ln12_fu_704_p1 = and_ln12_fu_698_p2;

assign zext_ln25_1_fu_971_p1 = select_ln25_fu_959_p3;

assign zext_ln25_2_fu_1579_p1 = t_5_fu_1488_p3;

assign zext_ln25_3_fu_1583_p1 = select_ln25_2_fu_1571_p3;

assign zext_ln25_fu_967_p1 = t_2_fu_876_p3;

assign zext_ln47_1_fu_1760_p1 = tmp_32_fu_1752_p3;

assign zext_ln47_fu_1372_p1 = tmp_14_fu_1364_p3;

assign zext_ln70_1_fu_1942_p1 = ui_1_fu_1836_p3;

assign zext_ln70_fu_1715_p1 = ui_fu_1448_p3;

assign zext_ln76_1_fu_1882_p1 = tmp_40_fu_1874_p3;

assign zext_ln76_2_fu_1954_p1 = tmp_41_reg_2918;

assign zext_ln76_3_fu_2306_p1 = and_ln76_fu_2300_p2;

assign zext_ln76_4_fu_2028_p1 = tmp_51_fu_2020_p3;

assign zext_ln76_5_fu_2049_p1 = tmp_52_fu_2041_p3;

assign zext_ln76_6_fu_2143_p1 = tmp_53_reg_3058;

assign zext_ln76_7_fu_2464_p1 = and_ln76_3_fu_2458_p2;

assign zext_ln76_fu_1861_p1 = tmp_39_fu_1853_p3;

endmodule //eclair_forward_layer_2_1_s
