// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eclair_eclair,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.535312,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=514,HLS_SYN_LUT=2680,HLS_VERSION=2024_1}" *)

module eclair (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r,
        output_r,
        output_r_ap_vld,
        feedback
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] input_r;
output  [15:0] output_r;
output   output_r_ap_vld;
input  [15:0] feedback;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_r_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53;
reg   [7:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52;
reg   [7:0] LUT_B0_address0;
reg    LUT_B0_ce0;
wire   [7:0] LUT_B0_q0;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q0;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q1;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q0;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q1;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q0;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q1;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q0;
reg   [0:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1;
reg    eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1;
wire   [15:0] eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q1;
reg   [7:0] LUT_B1_address0;
reg    LUT_B1_ce0;
wire   [9:0] LUT_B1_q0;
reg   [7:0] LUT_B2_address0;
reg    LUT_B2_ce0;
wire   [9:0] LUT_B2_q0;
reg   [7:0] LUT_B3_address0;
reg    LUT_B3_ce0;
wire   [7:0] LUT_B3_q0;
wire    ap_CS_fsm_state6;
reg    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_start;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_done;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_idle;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_ready;
wire   [7:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B0_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B0_ce0;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1;
wire   [15:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_d1;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1;
wire   [15:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_d1;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1;
wire   [15:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_d1;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0;
wire   [0:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1;
wire   [15:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_d1;
wire   [7:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B1_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B1_ce0;
wire   [7:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B2_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B2_ce0;
wire   [7:0] grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B3_address0;
wire    grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B3_ce0;
wire    grp_forward_layer_1_1_s_fu_105_ap_start;
wire    grp_forward_layer_1_1_s_fu_105_ap_done;
wire    grp_forward_layer_1_1_s_fu_105_ap_idle;
wire    grp_forward_layer_1_1_s_fu_105_ap_ready;
wire   [2:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53_ap_vld;
wire   [7:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52_ap_vld;
wire   [7:0] grp_forward_layer_1_1_s_fu_105_LUT_B0_address0;
wire    grp_forward_layer_1_1_s_fu_105_LUT_B0_ce0;
wire   [7:0] grp_forward_layer_1_1_s_fu_105_LUT_B1_address0;
wire    grp_forward_layer_1_1_s_fu_105_LUT_B1_ce0;
wire   [7:0] grp_forward_layer_1_1_s_fu_105_LUT_B2_address0;
wire    grp_forward_layer_1_1_s_fu_105_LUT_B2_ce0;
wire   [7:0] grp_forward_layer_1_1_s_fu_105_LUT_B3_address0;
wire    grp_forward_layer_1_1_s_fu_105_LUT_B3_ce0;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0;
wire   [0:0] grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1;
wire    grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1;
wire   [15:0] grp_forward_layer_1_1_s_fu_105_ap_return;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_forward_layer_1_1_s_fu_105_ap_start_reg;
wire    ap_CS_fsm_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53 = 3'd0;
#0 eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52 = 8'd0;
#0 grp_forward_layer_1_1_s_fu_105_ap_start_reg = 1'b0;
end

eclair_LUT_B0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
LUT_B0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LUT_B0_address0),
    .ce0(LUT_B0_ce0),
    .q0(LUT_B0_q0)
);

eclair_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_RAM_2P_LUTRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0),
    .ce0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0),
    .q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q0),
    .address1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1),
    .ce1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1),
    .we1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1),
    .d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_d1),
    .q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q1)
);

eclair_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_RAM_2P_LUTRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0),
    .ce0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0),
    .q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q0),
    .address1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1),
    .ce1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1),
    .we1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1),
    .d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_d1),
    .q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q1)
);

eclair_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_RAM_2P_LUTRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0),
    .ce0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0),
    .q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q0),
    .address1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1),
    .ce1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1),
    .we1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1),
    .d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_d1),
    .q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q1)
);

eclair_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_RAM_2P_LUTRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0),
    .ce0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0),
    .q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q0),
    .address1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1),
    .ce1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1),
    .we1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1),
    .d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_d1),
    .q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q1)
);

eclair_LUT_B1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 10 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
LUT_B1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LUT_B1_address0),
    .ce0(LUT_B1_ce0),
    .q0(LUT_B1_q0)
);

eclair_LUT_B2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 10 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
LUT_B2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LUT_B2_address0),
    .ce0(LUT_B2_ce0),
    .q0(LUT_B2_q0)
);

eclair_LUT_B3_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
LUT_B3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LUT_B3_address0),
    .ce0(LUT_B3_ce0),
    .q0(LUT_B3_q0)
);

eclair_backward_input_1_1_ap_fixed_16_6_4_0_0_s grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_start),
    .ap_done(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_done),
    .ap_idle(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_idle),
    .ap_ready(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_ready),
    .dL_dy_val(feedback),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52),
    .LUT_B0_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B0_address0),
    .LUT_B0_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B0_ce0),
    .LUT_B0_q0(LUT_B0_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_d1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_d1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_d1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_d1(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_d1),
    .LUT_B1_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B1_address0),
    .LUT_B1_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B1_ce0),
    .LUT_B1_q0(LUT_B1_q0),
    .LUT_B2_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B2_address0),
    .LUT_B2_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B2_ce0),
    .LUT_B2_q0(LUT_B2_q0),
    .LUT_B3_address0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B3_address0),
    .LUT_B3_ce0(grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B3_ce0),
    .LUT_B3_q0(LUT_B3_q0)
);

eclair_forward_layer_1_1_s grp_forward_layer_1_1_s_fu_105(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_layer_1_1_s_fu_105_ap_start),
    .ap_done(grp_forward_layer_1_1_s_fu_105_ap_done),
    .ap_idle(grp_forward_layer_1_1_s_fu_105_ap_idle),
    .ap_ready(grp_forward_layer_1_1_s_fu_105_ap_ready),
    .x_val(input_r),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53_ap_vld(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53_ap_vld),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52_ap_vld(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52_ap_vld),
    .LUT_B0_address0(grp_forward_layer_1_1_s_fu_105_LUT_B0_address0),
    .LUT_B0_ce0(grp_forward_layer_1_1_s_fu_105_LUT_B0_ce0),
    .LUT_B0_q0(LUT_B0_q0),
    .LUT_B1_address0(grp_forward_layer_1_1_s_fu_105_LUT_B1_address0),
    .LUT_B1_ce0(grp_forward_layer_1_1_s_fu_105_LUT_B1_ce0),
    .LUT_B1_q0(LUT_B1_q0),
    .LUT_B2_address0(grp_forward_layer_1_1_s_fu_105_LUT_B2_address0),
    .LUT_B2_ce0(grp_forward_layer_1_1_s_fu_105_LUT_B2_ce0),
    .LUT_B2_q0(LUT_B2_q0),
    .LUT_B3_address0(grp_forward_layer_1_1_s_fu_105_LUT_B3_address0),
    .LUT_B3_ce0(grp_forward_layer_1_1_s_fu_105_LUT_B3_ce0),
    .LUT_B3_q0(LUT_B3_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_q1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_q1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_q1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q0(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q0),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1(grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1),
    .eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q1(eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_q1),
    .ap_return(grp_forward_layer_1_1_s_fu_105_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_layer_1_1_s_fu_105_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_forward_layer_1_1_s_fu_105_ap_start_reg <= 1'b1;
        end else if ((grp_forward_layer_1_1_s_fu_105_ap_ready == 1'b1)) begin
            grp_forward_layer_1_1_s_fu_105_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53_ap_vld == 1'b1))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53 <= grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_k_53;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52_ap_vld == 1'b1))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52 <= grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_C_u_index_52;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B0_address0 = grp_forward_layer_1_1_s_fu_105_LUT_B0_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B0_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B0_address0;
    end else begin
        LUT_B0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B0_ce0 = grp_forward_layer_1_1_s_fu_105_LUT_B0_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B0_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B0_ce0;
    end else begin
        LUT_B0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B1_address0 = grp_forward_layer_1_1_s_fu_105_LUT_B1_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B1_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B1_address0;
    end else begin
        LUT_B1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B1_ce0 = grp_forward_layer_1_1_s_fu_105_LUT_B1_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B1_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B1_ce0;
    end else begin
        LUT_B1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B2_address0 = grp_forward_layer_1_1_s_fu_105_LUT_B2_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B2_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B2_address0;
    end else begin
        LUT_B2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B2_ce0 = grp_forward_layer_1_1_s_fu_105_LUT_B2_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B2_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B2_ce0;
    end else begin
        LUT_B2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B3_address0 = grp_forward_layer_1_1_s_fu_105_LUT_B3_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B3_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B3_address0;
    end else begin
        LUT_B3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LUT_B3_ce0 = grp_forward_layer_1_1_s_fu_105_LUT_B3_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        LUT_B3_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_LUT_B3_ce0;
    end else begin
        LUT_B3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_layer_1_1_s_fu_105_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_forward_layer_1_1_s_fu_105_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_forward_layer_1_1_s_fu_105_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1 = grp_forward_layer_1_1_s_fu_105_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1 = grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1;
    end else begin
        eclair_ap_fixed_const_ap_fixed_ap_fixed_16_6_4_0_0_const_P_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_start = 1'b1;
    end else begin
        grp_backward_input_1_1_ap_fixed_16_6_4_0_0_s_fu_79_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_forward_layer_1_1_s_fu_105_ap_done == 1'b1))) begin
        output_r_ap_vld = 1'b1;
    end else begin
        output_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_forward_layer_1_1_s_fu_105_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign grp_forward_layer_1_1_s_fu_105_ap_start = grp_forward_layer_1_1_s_fu_105_ap_start_reg;

assign output_r = grp_forward_layer_1_1_s_fu_105_ap_return;

endmodule //eclair
