// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp_mlp,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.599063,HLS_SYN_LAT=842,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=16367,HLS_SYN_LUT=65719,HLS_VERSION=2024_1}" *)

module mlp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r,
        output_r,
        output_r_ap_vld,
        feedback,
        zero_grad
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] input_r;
output  [15:0] output_r;
output   output_r_ap_vld;
input  [15:0] feedback;
input  [1:0] zero_grad;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_r_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] P_L1_b_102;
reg   [6:0] P_L1_W_0_address0;
reg    P_L1_W_0_ce0;
reg    P_L1_W_0_we0;
wire   [15:0] P_L1_W_0_q0;
reg    P_L1_W_0_ce1;
reg    P_L1_W_0_we1;
wire   [15:0] P_L1_W_0_q1;
reg   [6:0] C_C1_x_copy_address0;
reg    C_C1_x_copy_ce0;
reg    C_C1_x_copy_we0;
wire   [14:0] C_C1_x_copy_q0;
reg    C_C1_x_copy_ce1;
reg    C_C1_x_copy_we1;
reg   [15:0] mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy;
reg   [6:0] C_C0_z_address0;
reg    C_C0_z_ce0;
reg    C_C0_z_we0;
wire   [15:0] C_C0_z_q0;
reg   [6:0] P_L0_b_address0;
reg    P_L0_b_ce0;
reg    P_L0_b_we0;
wire   [15:0] P_L0_b_q0;
reg    P_L0_b_ce1;
wire   [15:0] P_L0_b_q1;
reg   [6:0] P_L0_W_0_address0;
reg    P_L0_W_0_ce0;
reg    P_L0_W_0_we0;
wire   [15:0] P_L0_W_0_q0;
reg    P_L0_W_0_ce1;
reg    P_L0_W_0_we1;
wire   [15:0] P_L0_W_0_q1;
wire   [0:0] icmp_ln22_fu_141_p2;
reg   [0:0] icmp_ln22_reg_153;
wire    ap_CS_fsm_state5;
reg   [6:0] layer1_out_address0;
reg    layer1_out_ce0;
reg    layer1_out_we0;
wire   [14:0] layer1_out_q0;
reg   [6:0] dL_dx_0_address0;
reg    dL_dx_0_ce0;
reg    dL_dx_0_we0;
wire   [15:0] dL_dx_0_q0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_ap_start;
wire    grp_mlp_Pipeline_FWD_O_fu_89_ap_done;
wire    grp_mlp_Pipeline_FWD_O_fu_89_ap_idle;
wire    grp_mlp_Pipeline_FWD_O_fu_89_ap_ready;
wire   [6:0] grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_address0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_ce0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_we0;
wire   [14:0] grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_d0;
wire   [6:0] grp_mlp_Pipeline_FWD_O_fu_89_P_L0_b_address0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_P_L0_b_ce0;
wire   [6:0] grp_mlp_Pipeline_FWD_O_fu_89_P_L0_W_0_address0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_P_L0_W_0_ce0;
wire   [6:0] grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_address0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_ce0;
wire    grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_we0;
wire   [15:0] grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_d0;
wire    grp_forward_output_layer_128_1_s_fu_103_ap_start;
wire    grp_forward_output_layer_128_1_s_fu_103_ap_done;
wire    grp_forward_output_layer_128_1_s_fu_103_ap_idle;
wire    grp_forward_output_layer_128_1_s_fu_103_ap_ready;
wire   [6:0] grp_forward_output_layer_128_1_s_fu_103_x_address0;
wire    grp_forward_output_layer_128_1_s_fu_103_x_ce0;
wire   [6:0] grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_address0;
wire    grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_ce0;
wire    grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_we0;
wire   [14:0] grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_d0;
wire   [6:0] grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_address1;
wire    grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_ce1;
wire    grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_we1;
wire   [14:0] grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_d1;
wire   [6:0] grp_forward_output_layer_128_1_s_fu_103_P_L1_W_0_address0;
wire    grp_forward_output_layer_128_1_s_fu_103_P_L1_W_0_ce0;
wire   [15:0] grp_forward_output_layer_128_1_s_fu_103_ap_return;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_done;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_idle;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_ready;
wire   [6:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_address0;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_ce0;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_we0;
wire   [15:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_d0;
wire   [15:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_b_102_o;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_b_102_o_ap_vld;
wire   [6:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_address0;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_ce0;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_we0;
wire   [15:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_d0;
wire   [6:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_address1;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_ce1;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_we1;
wire   [15:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_d1;
wire   [6:0] grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_C_C1_x_copy_address0;
wire    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_C_C1_x_copy_ce0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_done;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_idle;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_ready;
wire   [6:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_dL_dy_address0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_dL_dy_ce0;
wire   [6:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_C_C0_z_address0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_C_C0_z_ce0;
wire   [6:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_address0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_ce0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_we0;
wire   [15:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_d0;
wire   [6:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_address1;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_ce1;
wire   [6:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_address0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_ce0;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_we0;
wire   [15:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_d0;
wire   [6:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_address1;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_ce1;
wire    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_we1;
wire   [15:0] grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_d1;
reg    grp_mlp_Pipeline_FWD_O_fu_89_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_forward_output_layer_128_1_s_fu_103_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    ap_block_state8_on_subcall_done;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 P_L1_b_102 = 16'd65461;
#0 mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy = 16'd0;
#0 grp_mlp_Pipeline_FWD_O_fu_89_ap_start_reg = 1'b0;
#0 grp_forward_output_layer_128_1_s_fu_103_ap_start_reg = 1'b0;
#0 grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start_reg = 1'b0;
#0 grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start_reg = 1'b0;
end

mlp_P_L1_W_0_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
P_L1_W_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(P_L1_W_0_address0),
    .ce0(P_L1_W_0_ce0),
    .we0(P_L1_W_0_we0),
    .d0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_d0),
    .q0(P_L1_W_0_q0),
    .address1(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_address1),
    .ce1(P_L1_W_0_ce1),
    .we1(P_L1_W_0_we1),
    .d1(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_d1),
    .q1(P_L1_W_0_q1)
);

mlp_C_C1_x_copy_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
C_C1_x_copy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(C_C1_x_copy_address0),
    .ce0(C_C1_x_copy_ce0),
    .we0(C_C1_x_copy_we0),
    .d0(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_d0),
    .q0(C_C1_x_copy_q0),
    .address1(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_address1),
    .ce1(C_C1_x_copy_ce1),
    .we1(C_C1_x_copy_we1),
    .d1(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_d1)
);

mlp_C_C0_z_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
C_C0_z_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(C_C0_z_address0),
    .ce0(C_C0_z_ce0),
    .we0(C_C0_z_we0),
    .d0(grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_d0),
    .q0(C_C0_z_q0)
);

mlp_P_L0_b_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
P_L0_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(P_L0_b_address0),
    .ce0(P_L0_b_ce0),
    .we0(P_L0_b_we0),
    .d0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_d0),
    .q0(P_L0_b_q0),
    .address1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_address1),
    .ce1(P_L0_b_ce1),
    .q1(P_L0_b_q1)
);

mlp_P_L0_W_0_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
P_L0_W_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(P_L0_W_0_address0),
    .ce0(P_L0_W_0_ce0),
    .we0(P_L0_W_0_we0),
    .d0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_d0),
    .q0(P_L0_W_0_q0),
    .address1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_address1),
    .ce1(P_L0_W_0_ce1),
    .we1(P_L0_W_0_we1),
    .d1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_d1),
    .q1(P_L0_W_0_q1)
);

mlp_layer1_out_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
layer1_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer1_out_address0),
    .ce0(layer1_out_ce0),
    .we0(layer1_out_we0),
    .d0(grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_d0),
    .q0(layer1_out_q0)
);

mlp_dL_dx_0_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
dL_dx_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dL_dx_0_address0),
    .ce0(dL_dx_0_ce0),
    .we0(dL_dx_0_we0),
    .d0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_d0),
    .q0(dL_dx_0_q0)
);

mlp_mlp_Pipeline_FWD_O grp_mlp_Pipeline_FWD_O_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mlp_Pipeline_FWD_O_fu_89_ap_start),
    .ap_done(grp_mlp_Pipeline_FWD_O_fu_89_ap_done),
    .ap_idle(grp_mlp_Pipeline_FWD_O_fu_89_ap_idle),
    .ap_ready(grp_mlp_Pipeline_FWD_O_fu_89_ap_ready),
    .conv7_i_i(input_r),
    .layer1_out_address0(grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_address0),
    .layer1_out_ce0(grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_ce0),
    .layer1_out_we0(grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_we0),
    .layer1_out_d0(grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_d0),
    .P_L0_b_address0(grp_mlp_Pipeline_FWD_O_fu_89_P_L0_b_address0),
    .P_L0_b_ce0(grp_mlp_Pipeline_FWD_O_fu_89_P_L0_b_ce0),
    .P_L0_b_q0(P_L0_b_q0),
    .P_L0_W_0_address0(grp_mlp_Pipeline_FWD_O_fu_89_P_L0_W_0_address0),
    .P_L0_W_0_ce0(grp_mlp_Pipeline_FWD_O_fu_89_P_L0_W_0_ce0),
    .P_L0_W_0_q0(P_L0_W_0_q0),
    .C_C0_z_address0(grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_address0),
    .C_C0_z_ce0(grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_ce0),
    .C_C0_z_we0(grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_we0),
    .C_C0_z_d0(grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_d0)
);

mlp_forward_output_layer_128_1_s grp_forward_output_layer_128_1_s_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_output_layer_128_1_s_fu_103_ap_start),
    .ap_done(grp_forward_output_layer_128_1_s_fu_103_ap_done),
    .ap_idle(grp_forward_output_layer_128_1_s_fu_103_ap_idle),
    .ap_ready(grp_forward_output_layer_128_1_s_fu_103_ap_ready),
    .x_address0(grp_forward_output_layer_128_1_s_fu_103_x_address0),
    .x_ce0(grp_forward_output_layer_128_1_s_fu_103_x_ce0),
    .x_q0(layer1_out_q0),
    .P_L1_b_102(P_L1_b_102),
    .C_C1_x_copy_address0(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_address0),
    .C_C1_x_copy_ce0(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_ce0),
    .C_C1_x_copy_we0(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_we0),
    .C_C1_x_copy_d0(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_d0),
    .C_C1_x_copy_address1(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_address1),
    .C_C1_x_copy_ce1(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_ce1),
    .C_C1_x_copy_we1(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_we1),
    .C_C1_x_copy_d1(grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_d1),
    .P_L1_W_0_address0(grp_forward_output_layer_128_1_s_fu_103_P_L1_W_0_address0),
    .P_L1_W_0_ce0(grp_forward_output_layer_128_1_s_fu_103_P_L1_W_0_ce0),
    .P_L1_W_0_q0(P_L1_W_0_q0),
    .ap_return(grp_forward_output_layer_128_1_s_fu_103_ap_return)
);

mlp_backward_output_128_1_ap_fixed_16_6_4_0_0_s grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start),
    .ap_done(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_done),
    .ap_idle(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_idle),
    .ap_ready(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_ready),
    .dL_dx_address0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_address0),
    .dL_dx_ce0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_ce0),
    .dL_dx_we0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_we0),
    .dL_dx_d0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_d0),
    .dL_dy_val(feedback),
    .P_L1_b_102_i(P_L1_b_102),
    .P_L1_b_102_o(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_b_102_o),
    .P_L1_b_102_o_ap_vld(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_b_102_o_ap_vld),
    .P_L1_W_0_address0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_address0),
    .P_L1_W_0_ce0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_ce0),
    .P_L1_W_0_we0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_we0),
    .P_L1_W_0_d0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_d0),
    .P_L1_W_0_q0(P_L1_W_0_q0),
    .P_L1_W_0_address1(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_address1),
    .P_L1_W_0_ce1(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_ce1),
    .P_L1_W_0_we1(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_we1),
    .P_L1_W_0_d1(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_d1),
    .P_L1_W_0_q1(P_L1_W_0_q1),
    .C_C1_x_copy_address0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_C_C1_x_copy_address0),
    .C_C1_x_copy_ce0(grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_C_C1_x_copy_ce0),
    .C_C1_x_copy_q0(C_C1_x_copy_q0)
);

mlp_backward_input_1_128_ap_fixed_16_6_4_0_0_s grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start),
    .ap_done(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_done),
    .ap_idle(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_idle),
    .ap_ready(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_ready),
    .dL_dy_address0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_dL_dy_address0),
    .dL_dy_ce0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_dL_dy_ce0),
    .dL_dy_q0(dL_dx_0_q0),
    .mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy(mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy),
    .C_C0_z_address0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_C_C0_z_address0),
    .C_C0_z_ce0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_C_C0_z_ce0),
    .C_C0_z_q0(C_C0_z_q0),
    .P_L0_b_address0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_address0),
    .P_L0_b_ce0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_ce0),
    .P_L0_b_we0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_we0),
    .P_L0_b_d0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_d0),
    .P_L0_b_address1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_address1),
    .P_L0_b_ce1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_ce1),
    .P_L0_b_q1(P_L0_b_q1),
    .P_L0_W_0_address0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_address0),
    .P_L0_W_0_ce0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_ce0),
    .P_L0_W_0_we0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_we0),
    .P_L0_W_0_d0(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_d0),
    .P_L0_W_0_address1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_address1),
    .P_L0_W_0_ce1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_ce1),
    .P_L0_W_0_we1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_we1),
    .P_L0_W_0_d1(grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_d1),
    .P_L0_W_0_q1(P_L0_W_0_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_ready == 1'b1)) begin
            grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_ready == 1'b1)) begin
            grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_output_layer_128_1_s_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_forward_output_layer_128_1_s_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_forward_output_layer_128_1_s_fu_103_ap_ready == 1'b1)) begin
            grp_forward_output_layer_128_1_s_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mlp_Pipeline_FWD_O_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_ln22_fu_141_p2 == 1'd0))) begin
            grp_mlp_Pipeline_FWD_O_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_Pipeline_FWD_O_fu_89_ap_ready == 1'b1)) begin
            grp_mlp_Pipeline_FWD_O_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_b_102_o_ap_vld == 1'b1))) begin
        P_L1_b_102 <= grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_b_102_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln22_reg_153 <= icmp_ln22_fu_141_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_ln22_fu_141_p2 == 1'd0))) begin
        mlp_ap_fixed_const_ap_fixed_ap_fixed_const_ap_uint_2_C_C0_x_copy <= input_r;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        C_C0_z_address0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_C_C0_z_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_C0_z_address0 = grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_address0;
    end else begin
        C_C0_z_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        C_C0_z_ce0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_C_C0_z_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_C0_z_ce0 = grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_ce0;
    end else begin
        C_C0_z_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_C0_z_we0 = grp_mlp_Pipeline_FWD_O_fu_89_C_C0_z_we0;
    end else begin
        C_C0_z_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_C1_x_copy_address0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_C_C1_x_copy_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        C_C1_x_copy_address0 = grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_address0;
    end else begin
        C_C1_x_copy_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_C1_x_copy_ce0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_C_C1_x_copy_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        C_C1_x_copy_ce0 = grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_ce0;
    end else begin
        C_C1_x_copy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_C1_x_copy_ce1 = grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_ce1;
    end else begin
        C_C1_x_copy_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_C1_x_copy_we0 = grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_we0;
    end else begin
        C_C1_x_copy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_C1_x_copy_we1 = grp_forward_output_layer_128_1_s_fu_103_C_C1_x_copy_we1;
    end else begin
        C_C1_x_copy_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_W_0_address0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        P_L0_W_0_address0 = grp_mlp_Pipeline_FWD_O_fu_89_P_L0_W_0_address0;
    end else begin
        P_L0_W_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_W_0_ce0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        P_L0_W_0_ce0 = grp_mlp_Pipeline_FWD_O_fu_89_P_L0_W_0_ce0;
    end else begin
        P_L0_W_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_W_0_ce1 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_ce1;
    end else begin
        P_L0_W_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_W_0_we0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_we0;
    end else begin
        P_L0_W_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_W_0_we1 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_W_0_we1;
    end else begin
        P_L0_W_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_b_address0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        P_L0_b_address0 = grp_mlp_Pipeline_FWD_O_fu_89_P_L0_b_address0;
    end else begin
        P_L0_b_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_b_ce0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        P_L0_b_ce0 = grp_mlp_Pipeline_FWD_O_fu_89_P_L0_b_ce0;
    end else begin
        P_L0_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_b_ce1 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_ce1;
    end else begin
        P_L0_b_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        P_L0_b_we0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_P_L0_b_we0;
    end else begin
        P_L0_b_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        P_L1_W_0_address0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        P_L1_W_0_address0 = grp_forward_output_layer_128_1_s_fu_103_P_L1_W_0_address0;
    end else begin
        P_L1_W_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        P_L1_W_0_ce0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        P_L1_W_0_ce0 = grp_forward_output_layer_128_1_s_fu_103_P_L1_W_0_ce0;
    end else begin
        P_L1_W_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        P_L1_W_0_ce1 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_ce1;
    end else begin
        P_L1_W_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        P_L1_W_0_we0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_we0;
    end else begin
        P_L1_W_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        P_L1_W_0_we1 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_P_L1_W_0_we1;
    end else begin
        P_L1_W_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mlp_Pipeline_FWD_O_fu_89_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_output_layer_128_1_s_fu_103_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        dL_dx_0_address0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_dL_dy_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        dL_dx_0_address0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_address0;
    end else begin
        dL_dx_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln22_reg_153 == 1'd1))) begin
        dL_dx_0_ce0 = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_dL_dy_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        dL_dx_0_ce0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_ce0;
    end else begin
        dL_dx_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dL_dx_0_we0 = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_dL_dx_we0;
    end else begin
        dL_dx_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer1_out_address0 = grp_forward_output_layer_128_1_s_fu_103_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer1_out_address0 = grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_address0;
    end else begin
        layer1_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer1_out_ce0 = grp_forward_output_layer_128_1_s_fu_103_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer1_out_ce0 = grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_ce0;
    end else begin
        layer1_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer1_out_we0 = grp_mlp_Pipeline_FWD_O_fu_89_layer1_out_we0;
    end else begin
        layer1_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_forward_output_layer_128_1_s_fu_103_ap_done == 1'b1))) begin
        output_r_ap_vld = 1'b1;
    end else begin
        output_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_ln22_fu_141_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_ln22_fu_141_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_mlp_Pipeline_FWD_O_fu_89_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_forward_output_layer_128_1_s_fu_103_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_done == 1'b0) & (icmp_ln22_reg_153 == 1'd1));
end

assign grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start = grp_backward_input_1_128_ap_fixed_16_6_4_0_0_s_fu_128_ap_start_reg;

assign grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start = grp_backward_output_128_1_ap_fixed_16_6_4_0_0_s_fu_115_ap_start_reg;

assign grp_forward_output_layer_128_1_s_fu_103_ap_start = grp_forward_output_layer_128_1_s_fu_103_ap_start_reg;

assign grp_mlp_Pipeline_FWD_O_fu_89_ap_start = grp_mlp_Pipeline_FWD_O_fu_89_ap_start_reg;

assign icmp_ln22_fu_141_p2 = ((zero_grad == 2'd0) ? 1'b1 : 1'b0);

assign output_r = grp_forward_output_layer_128_1_s_fu_103_ap_return;

endmodule //mlp
